const questionDB = [
    { id: 1, target: "부부 공통", category: "위로", question: "오늘 하루, 육아로 고생한 서로의 어깨를 주무르며 해주고 싶은 말은 무엇인가요?" },
    { id: 2, target: "남편", category: "사랑", question: "아내가 아기를 바라볼 때, 가장 아름답고 고맙다고 느낀 순간은 언제였나요?" },
    { id: 3, target: "아내", category: "사랑", question: "남편이 아빠로서 가장 든든하게 느껴졌던 최근의 순간은 언제인가요?" },
    { id: 4, target: "가족", category: "성장", question: "{babyName}가 우리 가족에게 찾아온 후, 우리 집의 공기와 분위기는 어떻게 달라졌나요?" },
    { id: 5, target: "부부 공통", category: "추억", question: "아기가 태어나기 전, 우리가 단둘이 보냈던 가장 행복했던 데이트는 언제였나요?" },
    { id: 6, target: "아내", category: "위로", question: "오늘 하루 중, 몸이나 마음이 가장 지쳤던 순간은 언제였나요?" },
    { id: 7, target: "남편", category: "위로", question: "아내가 가장 안쓰러워 보였을 때, 당신은 마음속으로 어떤 다짐을 했나요?" },
    { id: 8, target: "가족", category: "미래", question: "우리 세 식구가 처음으로 다 같이 1박 2일 여행을 간다면 어디로 가고 싶나요?" },
    { id: 9, target: "부부 공통", category: "감사", question: "서로의 육아 방식 중, 내가 가지지 못해 고맙고 본받고 싶은 점은 무엇인가요?" },
    { id: 10, target: "아내", category: "추억", question: "임신 사실을 처음 알았을 때, 남편의 표정을 기억하나요?" },
    { id: 11, target: "남편", category: "추억", question: "출산하던 날, 분만실 앞(또는 안)에서 당신이 느꼈던 가장 강렬한 감정은?" },
    { id: 12, target: "가족", category: "일상", question: "오늘 {babyName}의 행동 중 우리 부부를 가장 크게 웃게 만든 일은 무엇인가요?" },
    { id: 13, target: "부부 공통", category: "사랑", question: "결혼 전 연애할 때, 서로를 부르던 애칭은 무엇이었나요? 지금 한 번 불러볼까요?" },
    { id: 14, target: "아내", category: "감사", question: "남편이 말없이 집안일이나 육아를 도와주었을 때, 가장 감동받았던 순간은?" },
    { id: 15, target: "남편", category: "감사", question: "아내가 피곤한 와중에도 나를 위해 배려해주었다고 느낀 순간은 언제인가요?" },
    { id: 16, target: "가족", category: "미래", question: "{babyName}가 10살이 되면, 주말에 셋이서 어떤 취미를 공유하고 싶나요?" },
    { id: 17, target: "부부 공통", category: "위로", question: "만약 오늘 하루 5시간의 자유시간이 주어진다면, 각자 무엇을 하고 싶나요?" },
    { id: 18, target: "아내", category: "일상", question: "최근에 거울을 보며 스스로에게 가장 해주고 싶었던 말은 무엇인가요?" },
    { id: 19, target: "남편", category: "가족", question: "가장의 어깨가 무겁다고 느껴질 때, 당신을 다시 일어서게 하는 힘은 무엇인가요?" },
    { id: 20, target: "가족", category: "사랑", question: "우리 가족의 모습을 한 편의 영화 장르로 표현한다면 어떤 장르일까요?" },
    { id: 21, target: "부부 공통", category: "추억", 구question: "우리가 처음으로 크게 싸우고 화해했던 날, 서로에 대해 새롭게 알게 된 점은?" },
    { id: 22, target: "아내", category: "미래", question: "먼 훗날 아기가 커서 당신을 어떤 엄마로 기억해 주기를 바라나요?" },
    { id: 23, target: "남편", category: "미래", question: "아기가 자라면서 아빠에게 가장 많이 배웠으면 하는 가치관은 무엇인가요?" },
    { id: 24, target: "가족", category: "일상", question: "요즘 우리 가족 식탁에서 가장 자주 올라오는 이야기 주제는 무엇인가요?" },
    { id: 25, target: "부부 공통", category: "감사", question: "오늘 하루, 무사히 지나간 것만으로도 다행이라고 느꼈던 순간은?" },
    { id: 26, target: "아내", category: "위로", question: "육아 우울감이나 피로가 몰려올 때, 남편의 어떤 행동이 가장 큰 위로가 되나요?" },
    { id: 27, target: "남편", category: "사랑", question: "당신의 눈에 비친 아내는 결혼 전과 비교해서 어떻게 더 아름다워졌나요?" },
    { id: 28, target: "가족", category: "미래", question: "우리 가족이 살고 싶은 궁극적인 '꿈의 집'은 어떤 모습인가요?" },
    { id: 29, target: "부부 공통", category: "사랑", question: "서로의 잠든 얼굴을 가만히 바라볼 때, 어떤 생각이 드나요?" },
    { id: 30, target: "아내", category: "일상", question: "육아를 하면서 새롭게 알게 된 나 자신의 의외의 모습이 있다면?" },
    { id: 31, target: "남편", category: "일상", question: "아빠가 된 후, 퇴근길 발걸음이나 마음가짐이 어떻게 달라졌나요?" },
    { id: 32, target: "가족", category: "추억", question: "세 식구가 함께 찍은 사진 중, 가장 마음에 드는 사진은 어떤 사진인가요?" },
    { id: 33, target: "부부 공통", category: "위로", question: "가끔 우리가 부족한 부모라고 자책할 때, 서로에게 어떤 응원을 해주고 싶나요?" },
    { id: 34, target: "아내", category: "사랑", question: "당신이 남편에게 가장 사랑받고 있다고 느끼는 일상 속 소소한 행동은?" },
    { id: 35, target: "남편", category: "감사", question: "아내가 엄마로서 겪는 희생에 대해 가장 고맙고 미안한 점은 무엇인가요?" },
    { id: 36, target: "가족", category: "미래", question: "{babyName}가 어린이집/유치원에 처음 가는 날, 우리 부부의 기분은 어떨까요?" },
    { id: 37, target: "부부 공통", category: "추억", question: "결혼식 날, 우리가 서로에게 했던 맹세나 다짐 중 가장 잘 지키고 있는 것은?" },
    { id: 38, target: "아내", category: "일상", question: "최근에 육아하면서 가장 당황스럽거나 멘붕이 왔던 에피소드는?" },
    { id: 39, target: "남편", category: "성장", question: "아빠가 된 후, 나의 부모님을 이해하게 된 순간이 있나요?" },
    { id: 40, target: "가족", category: "사랑", question: "우리 세 사람만의 특별한 '스킨십'이나 '인사법'을 만들어본다면?" },
    { id: 41, target: "부부 공통", category: "위로", question: "오늘 밤은 육아 고민 다 내려놓고, 좋아하는 야식 메뉴 하나를 고른다면?" },
    { id: 42, target: "아내", category: "미래", question: "아기가 스스로 걸을 수 있게 되면 가장 먼저 손잡고 걷고 싶은 길은 어디인가요?" },
    { id: 43, target: "남편", category: "추억", question: "아내가 해준 음식 중, 평생 잊지 못할 만큼 맛있었던 요리는 무엇인가요?" },
    { id: 44, target: "가족", category: "성장", question: "우리가 부모로서 어제보다 오늘 더 잘 해냈다고 칭찬해줄 부분은?" },
    { id: 45, target: "부부 공통", category: "감사", question: "서로가 부모로서 완벽하지 않아도 괜찮다고 말해볼까요?" },
    { id: 46, target: "아내", category: "사랑", question: "결혼을 결심하게 만든 남편의 결정적인 매력은 지금도 유효한가요?" },
    { id: 47, target: "남편", category: "위로", question: "당신만의 동굴이 필요할 때, 아내가 어떻게 기다려주었으면 좋겠나요?" },
    { id: 48, target: "가족", category: "미래", question: "{babyName}가 처음으로 '엄마, 아빠 사랑해요'라고 말하는 날, 우리는 어떤 반응을 보일까요?" },
    { id: 49, target: "부부 공통", category: "추억", question: "아기 이름({babyName})을 처음 지었을 때, 우리가 나누었던 대화를 기억하나요?" },
    { id: 50, target: "아내", category: "일상", question: "오늘 가장 나다운 모습으로 보냈던 시간은 언제였나요?" },
    { id: 51, target: "남편", category: "감사", question: "아침에 눈을 떴을 때, 아내와 아기가 옆에 있는 걸 보며 드는 생각은?" },
    { id: 52, target: "가족", category: "성장", question: "요즘 아기가 부쩍 자랐다고 느끼는 가장 신기한 변화는 무엇인가요?" },
    { id: 53, target: "부부 공통", category: "위로", question: "수면 부족으로 예민해져서 서로에게 상처를 줬을 때, 가장 먼저 건넬 사과의 말은?" },
    { id: 54, target: "아내", category: "사랑", question: "당신을 향한 남편의 눈빛 중 가장 좋아하는 눈빛은?" },
    { id: 55, target: "남편", category: "미래", question: "아기가 크면, 아빠와 단둘이 꼭 해보고 싶은 버킷리스트는 무엇인가요?" },
    { id: 56, target: "가족", category: "추억", question: "우리 부부가 함께 들으면 연애 시절이 생각나는 '그 노래'는 무엇인가요?" },
    { id: 57, target: "부부 공통", category: "감사", question: "오늘 하루, 당신이 나의 배우자라서 다행이라고 느꼈던 순간은?" },
    { id: 58, target: "아내", category: "성장", question: "출산 전과 후, 삶의 우선순위가 어떻게 가장 크게 바뀌었나요?" },
    { id: 59, target: "남편", category: "위로", question: "남편이자 아빠로서 당신이 가장 위로받고 싶은 부분은 무엇인가요?" },
    { id: 60, target: "가족", category: "미래", question: "매년 우리 가족이 빼놓지 않고 꼭 지키고 싶은 연례행사가 있다면?" },
    { id: 61, target: "부부 공통", category: "사랑", question: "서로의 외모 중에서 아기가 꼭 닮았으면 하는 부분은 어디인가요?" },
    { id: 62, target: "아내", category: "추억", question: "결혼 준비를 하면서 가장 의견이 안 맞았지만 지금 생각하면 웃음 나는 일은?" },
    { id: 63, target: "남편", category: "일상", question: "요즘 당신을 가장 피곤하게 하는 것과 가장 기운 나게 하는 것은 무엇인가요?" },
    { id: 64, target: "가족", category: "감동", question: "아기가 잠결에 무의식적으로 우리를 찾거나 안길 때 어떤 감정이 드나요?" },
    { id: 65, target: "부부 공통", category: "감사", question: "부모가 되어보니, 나의 부모님께 새삼 감사하게 된 일은 무엇인가요?" },
    { id: 66, target: "아내", category: "위로", question: "아무도 모르게 혼자 울고 싶었던 날, 어떻게 마음을 다스렸나요?" },
    { id: 67, target: "남편", category: "사랑", question: "아내의 요리 중 당신의 영혼까지 따뜻하게 데워주는 메뉴는 무엇인가요?" },
    { id: 68, target: "가족", category: "미래", question: "우리 아이가 나중에 커서 어떤 성격의 친구를 사귀었으면 좋겠나요?" },
    { id: 69, target: "부부 공통", category: "추억", question: "첫 데이트 날, 우리는 서로에게 어떤 향기나 분위기로 기억되나요?" },
    { id: 70, target: "아내", category: "미래", question: "아기가 훌쩍 커서 부모의 손이 덜 필요해지면, 당신을 위해 가장 먼저 하고 싶은 일은?" },
    { id: 71, target: "남편", category: "추억", question: "신혼여행에서 있었던 일 중 가장 어이없고 재밌었던 에피소드는?" },
    { id: 72, target: "가족", category: "일상", question: "요즘 우리 집에서 가장 많이 들리는 소리는 무엇인가요? (울음, 웃음, 노래 등)" },
    { id: 73, target: "부부 공통", category: "사랑", question: "부부싸움을 한 뒤, 어색한 분위기를 깨기 위해 우리가 주로 쓰는 방법은?" },
    { id: 74, target: "아내", category: "감사", question: "남편이 나의 말을 가장 잘 경청해주었다고 느낀 최근의 대화는?" },
    { id: 75, target: "남편", category: "위로", question: "육아 외에 요즘 당신의 머릿속을 맴도는 가장 큰 고민은 무엇인가요?" },
    { id: 76, target: "가족", category: "성장", question: "우리가 부모가 되기 참 잘했다고 느껴지는 가장 확실한 증거는 무엇인가요?" },
    { id: 77, target: "부부 공통", category: "추억", question: "만약 시간을 돌려 연애 시절로 하루만 다녀올 수 있다면, 어느 날로 가고 싶나요?" },
    { id: 78, target: "아내", category: "사랑", question: "당신이 남편을 가장 존경스럽게 바라보게 되는 순간은?" },
    { id: 79, target: "남편", category: "감사", question: "아내가 나를 칭찬해주었을 때 가장 기분 좋았던 말은 무엇인가요?" },
    { id: 80, target: "가족", category: "미래", question: "10년 뒤, 오늘 쓴 이 일기장을 세 식구가 함께 펼쳐본다면 기분이 어떨까요?" },
    { id: 81, target: "부부 공통", category: "일상", question: "우리가 집에서 가장 편안함을 느끼는 각자의 공간이나 자세는?" },
    { id: 82, target: "아내", category: "추억", question: "우리의 결혼반지를 처음 끼던 날의 설렘을 한 문장으로 표현한다면?" },
    { id: 83, target: "남편", category: "사랑", question: "아내의 미소 중에서 당신을 가장 무장해제 시키는 표정은 어떤 표정인가요?" },
    { id: 84, target: "가족", category: "감사", question: "우리가 건강하게 오늘 하루를 보낼 수 있도록 도와준 주변 사람들에게 감사를 표해볼까요?" },
    { id: 85, target: "부부 공통", category: "위로", question: "서로의 건강을 위해 오늘부터 꼭 지키고 싶은 작은 약속 하나는?" },
    { id: 86, target: "아내", category: "미래", question: "딸/아들과 나중에 단둘이 데이트를 한다면 가고 싶은 곳은?" },
    { id: 87, target: "남편", category: "일상", question: "오늘 하루, 당신이 발견한 아주 소소하지만 확실한 행복은 무엇인가요?" },
    { id: 88, target: "가족", category: "성장", question: "아기가 실패하고 넘어질 때, 우리 부부는 어떤 태도로 기다려주어야 할까요?" },
    { id: 89, target: "부부 공통", category: "사랑", question: "우리가 70대 노부부가 되었을 때, 서로를 어떤 눈빛으로 바라보고 있을까요?" },
    { id: 90, target: "아내", category: "감동", question: "내 품에서 곤히 잠든 아기의 숨소리를 들을 때, 어떤 기적이 느껴지나요?" },
    { id: 91, target: "남편", category: "위로", question: "자신감이 떨어지거나 작아진다고 느낄 때, 아내의 어떤 말이 힘이 될까요?" },
    { id: 92, target: "가족", category: "추억", question: "아기가 처음으로 엄마/아빠의 목소리에 반응하고 웃었던 날을 기억하나요?" },
    { id: 93, target: "부부 공통", category: "일상", question: "비 오는 주말, 외출하지 않고 집에서 우리가 가장 재밌게 노는 방법은?" },
    { id: 94, target: "아내", category: "사랑", question: "남편의 잠든 얼굴을 볼 때면 가끔 어떤 짠한 마음이 드나요?" },
    { id: 95, target: "남편", category: "감사", question: "당신의 인생에 아내가 들어와서 가장 긍정적으로 변한 것은 무엇인가요?" },
    { id: 96, target: "가족", category: "미래", question: "우리가 가족이라는 이름으로 함께 이뤄내고 싶은 작은 목표 하나는?" },
    { id: 97, target: "부부 공통", category: "위로", question: "오늘 하루도 아무 사고 없이 잘 넘긴 서로의 머리를 쓰다듬어 주며 인사해 볼까요?" },
    { id: 98, target: "아내", category: "추억", question: "우리가 처음으로 함께 본 영화는 무엇이었고, 그때 느낌은 어땠나요?" },
    { id: 99, target: "남편", category: "성장", question: "아이의 눈을 통해 새롭게 깨닫게 된 세상의 아름다움이 있다면?" },
    { id: 100, target: "가족", category: "감동", question: "앞으로도 매일매일, 우리가 서로를 세상에서 가장 사랑하는 이유를 써 내려가 볼까요?" }
];