// ==========================================
// 🍼 육아메이트 이유식 통합 데이터베이스 (food/data.js)
// ※ AI 출력 한계치까지 밀어넣은 압도적 물량 (식재료 100종 + 레시피 70종)
// ==========================================

// 🚦 1. 식재료 신호등 데이터 (총 100종 완벽 분류)
const ingredientDB = [
    // 🔴 절대 금지
    { name: "꿀", status: "red", keywords: ["단거", "시럽", "올리고당", "허니"], desc: "돌 이전 절대 금지! 보툴리눔 독소증으로 호흡 마비 위험." },
    { name: "생우유", status: "red", keywords: ["우유", "밀크"], desc: "돌 이전 섭취 불가! 장 출혈 및 알레르기 위험." },
    { name: "소금", status: "red", keywords: ["간", "짠거", "조미료", "간장"], desc: "돌 이전 신장에 치명적입니다." },
    { name: "설탕", status: "red", keywords: ["단거", "사탕", "주스"], desc: "비만, 충치 원인 및 미각 발달 방해." },
    { name: "포도", status: "red", keywords: ["샤인머스캣", "거봉", "청포도"], desc: "질식 위험 1위! 껍질/씨 제거 후 4등분 필수." },
    { name: "방울토마토", status: "red", keywords: ["대추토마토"], desc: "질식 위험. 반드시 4등분 이상 자르세요." },
    { name: "통견과류", status: "red", keywords: ["아몬드", "땅콩", "호두", "잣"], desc: "기도로 넘어가면 치명적. 무조건 가루로 사용." },
    { name: "생선회", status: "red", keywords: ["날것", "회", "초밥", "육회"], desc: "식중독 및 기생충 위험 (세 돌 이전 피할 것)." },
    { name: "카페인", status: "red", keywords: ["커피", "녹차", "홍차", "초콜릿"], desc: "철분 흡수 방해 및 뇌 발달 악영향." },

    // 🟡 주의 및 고위험군
    { name: "돼지고기", status: "yellow", keywords: ["고기", "삼겹살", "목살"], desc: "기름기가 많아 소화가 어려움. 후기 이후 안심 위주 시도." },
    { name: "복숭아", status: "yellow", keywords: ["과일", "천도", "백도", "황도"], desc: "대표적 알레르기 과일. 돌~두 돌 이후 시도." },
    { name: "키위", status: "yellow", keywords: ["골드키위", "그린키위"], desc: "산도가 높고 씨가 알레르기 유발. 돌 이후 시도." },
    { name: "딸기", status: "yellow", keywords: ["베리", "산딸기"], desc: "씨와 표면 털이 알레르기 유발. 돌 이후 권장." },
    { name: "파인애플", status: "yellow", keywords: ["열대과일"], desc: "강한 산성. 돌 이후 푹 익혀서 소량 시도." },
    { name: "계란흰자", status: "yellow", keywords: ["달걀", "알", "흰자", "전란"], desc: "단백질 알레르기 위험. 돌 이후 테스트 필수!" },
    { name: "새우", status: "yellow", keywords: ["갑각류", "대하", "건새우"], desc: "갑각류 알레르기 위험. 완료기 이후 시도." },
    { name: "게", status: "yellow", keywords: ["갑각류", "크래미", "게살", "대게"], desc: "갑각류 알레르기 고위험군." },
    { name: "조개", status: "yellow", keywords: ["바지락", "홍합", "꼬막", "가리비", "전복"], desc: "중금속 및 알레르기 위험. 후기/돌 이후 완전히 익혀서 시도." },
    { name: "밀가루", status: "yellow", keywords: ["빵", "면", "소면", "밀", "파스타"], desc: "글루텐 알레르기 확인을 위해 초기~중기 3일 연속 소량 테스트." },
    { name: "대두", status: "yellow", keywords: ["콩", "두부", "순두부", "된장"], desc: "콩 알레르기 주의! 두부로 처음 접할 때 피부 관찰." },
    { name: "토마토", status: "yellow", keywords: ["과일", "채소"], desc: "산성이 강해 입 주변 붉어짐. 껍질 벗기고 익혀서 급여." },
    { name: "오징어", status: "yellow", keywords: ["문어", "낙지"], desc: "질겨서 씹기 어려움. 완료기 이후 아주 잘게 다져서 급여." },
    { name: "고등어", status: "yellow", keywords: ["등푸른생선", "꽁치", "참치"], desc: "알레르기 유발 확률이 높은 등푸른 생선. 돌 이후 권장." },

    // 🟢 안심 - 단백질 (고기/생선)
    { name: "소고기", status: "green", keywords: ["우둔살", "안심", "채끝", "다짐육"], desc: "생후 6개월 이후 필수! 철분 보충을 위해 매일 급여." },
    { name: "닭고기", status: "green", keywords: ["가슴살", "안심", "닭", "치킨"], desc: "소화가 잘되는 단백질원. 푹 삶아 사용." },
    { name: "흰살생선", status: "green", keywords: ["대구", "가자미", "동태", "광어", "갈치", "조기"], desc: "비린내가 적고 담백함. 가시 완벽 제거 필수." },
    { name: "연어", status: "green", keywords: ["붉은살생선", "연어구이"], desc: "두뇌 발달(오메가3)에 좋으나 기름기가 많아 후기(10개월~) 권장." },
    { name: "잔멸치", status: "green", keywords: ["지리멸치", "뼈"], desc: "칼슘 폭탄! 완료기 이후 물에 데쳐 짠기 빼고 다져서 사용." },
    { name: "오리고기", status: "green", keywords: ["오리", "훈제오리불가"], desc: "불포화지방산이 풍부. 후기 이후 생오리를 푹 익혀서 사용." },

    // 🟢 안심 - 곡류/슈퍼푸드
    { name: "쌀", status: "green", keywords: ["밥", "쌀가루", "죽", "진밥"], desc: "가장 알레르기 확률이 낮은 완벽한 첫 이유식 베이스." },
    { name: "현미", status: "green", keywords: ["잡곡"], desc: "영양이 풍부하지만 소화가 어려워 쌀과 섞어 푹 불려 사용." },
    { name: "보리", status: "green", keywords: ["잡곡"], desc: "구수한 맛이 나며 중기부터 쌀과 섞어 사용 가능." },
    { name: "수수", status: "green", keywords: ["잡곡", "찰수수"], desc: "항산화 성분이 많으나 떫은맛이 있어 푹 불리고 삶아서 소량 혼합." },
    { name: "찹쌀", status: "green", keywords: ["곡류", "찹쌀가루"], desc: "소화를 돕고 찰기를 더해줍니다. 초기부터 가능." },
    { name: "오트밀", status: "green", keywords: ["귀리", "퀵오트", "포리지"], desc: "철분/식이섬유 보고! 쌀가루 대신 쓰기 좋습니다." },
    { name: "퀴노아", status: "green", keywords: ["슈퍼푸드", "씨앗"], desc: "단백질 풍부. 중기부터 푹 불려서 쌀과 섞어 사용." },
    { name: "렌틸콩", status: "green", keywords: ["콩", "슈퍼푸드", "레드렌틸콩"], desc: "철분/단백질 풍부. 껍질 깐 레드 렌틸콩을 중기부터 사용." },
    { name: "병아리콩", status: "green", keywords: ["이집트콩", "콩"], desc: "밤처럼 고소함. 껍질을 완벽히 까고 푹 삶아 으깨주세요." },
    { name: "검은콩", status: "green", keywords: ["서리태", "콩"], desc: "단백질이 풍부하나 껍질이 질기므로 푹 불려 껍질 까고 갈아주세요." },
    { name: "고구마", status: "green", keywords: ["구황작물", "호박고구마"], desc: "초기부터 가능! 달콤하고 변비 예방에 탁월." },
    { name: "감자", status: "green", keywords: ["구황작물"], desc: "싹과 푸른 껍질(독성) 완벽히 도려내고 급여." },
    { name: "단호박", status: "green", keywords: ["미니단호박", "호박"], desc: "부드럽고 소화 잘됨. 질긴 껍질과 씨 제거." },
    { name: "밤", status: "green", keywords: ["알밤", "맛밤"], desc: "탄수화물과 비타민 풍부. 푹 쪄서 곱게 으깨주세요." },

    // 🟢 안심 - 채소류 (잎채소, 뿌리채소, 열매채소)
    { name: "청경채", status: "green", keywords: ["야채", "잎채소"], desc: "초기 가능. 질긴 줄기 버리고 이파리만 다져서 사용." },
    { name: "비타민", status: "green", keywords: ["다채", "야채", "잎채소"], desc: "철분 흡수를 돕는 초기 안심 채소." },
    { name: "브로콜리", status: "green", keywords: ["꽃채소", "야채"], desc: "비타민C 풍부. 질긴 기둥 버리고 꽃송이만 사용." },
    { name: "콜리플라워", status: "green", keywords: ["야채", "꽃채소"], desc: "브로콜리보다 식감이 부드러워 초기 채소로 훌륭." },
    { name: "애호박", status: "green", keywords: ["호박", "야채"], desc: "소화가 잘되는 초기 채소. 씨 부분 도려내고 껍질 벗겨 사용." },
    { name: "단호박", status: "green", keywords: ["호박", "야채"], desc: "달콤하고 부드러워 초기 베이스로 아주 좋습니다." },
    { name: "양배추", status: "green", keywords: ["잎채소", "적양배추", "야채"], desc: "위장에 좋고 단맛. 두꺼운 심지 제거 후 잎만 사용." },
    { name: "적채", status: "green", keywords: ["적양배추", "야채"], desc: "색감을 내기 좋으며 양배추와 조리법 동일." },
    { name: "오이", status: "green", keywords: ["야채"], desc: "수분이 많아 초기 간식으로 좋음. 씨 빼고 껍질 벗겨 사용." },
    { name: "시금치", status: "green", keywords: ["잎채소", "야채"], desc: "질산염 우려로 6개월 이후 사용, 데친 물은 꼭 버리세요." },
    { name: "근대", status: "green", keywords: ["잎채소", "야채"], desc: "시금치와 비슷하게 질산염 우려가 있으니 데친 물을 버리고 사용." },
    { name: "아욱", status: "green", keywords: ["잎채소", "야채"], desc: "질긴 줄기를 제거하고 바락바락 주물러 푸른 물을 빼고 부드럽게 끓여주세요." },
    { name: "배추", status: "green", keywords: ["알배기배추", "잎채소", "야채"], desc: "중기부터 가능. 시원하고 단맛이 납니다." },
    { name: "당근", status: "green", keywords: ["뿌리채소", "야채"], desc: "질산염 우려로 생후 6개월 이후 권장. 기름에 볶으면 흡수율 상승." },
    { name: "무", status: "green", keywords: ["뿌리채소", "야채"], desc: "소화 효소 풍부. 푹 익혀주세요." },
    { name: "양파", status: "green", keywords: ["적양파", "야채"], desc: "잡내 잡고 단맛을 냄. 매운맛 날아가도록 푹 익혀주세요." },
    { name: "대파", status: "green", keywords: ["파", "야채"], desc: "후기부터 육수용이나 아주 잘게 다져 볶음용으로 향을 내기 좋습니다." },
    { name: "비트", status: "green", keywords: ["레드비트", "야채"], desc: "철분 풍부. 질산염 주의(6개월 이후). 빨간 똥이 나올 수 있습니다." },
    { name: "연근", status: "green", keywords: ["뿌리채소", "야채"], desc: "철분/탄닌 풍부. 떫은맛 빼고 푹 익혀 아주 잘게 다지세요." },
    { name: "가지", status: "green", keywords: ["야채"], desc: "안토시아닌 풍부. 껍질 벗기고 익혀주세요." },
    { name: "파프리카", status: "green", keywords: ["피망", "야채"], desc: "비타민C 폭탄. 껍질이 질기니 끓는물에 데쳐 껍질을 까고 다져주세요." },
    { name: "아스파라거스", status: "green", keywords: ["야채"], desc: "질긴 껍질은 필러로 벗기고 부드러운 봉우리 위주로 다져주세요." },
    { name: "샐러리", status: "green", keywords: ["야채"], desc: "향이 강하므로 육수용으로 쓰거나 후기부터 아주 잘게 다져 고기 잡내를 잡을 때 쓰세요." },
    
    // 🟢 안심 - 버섯류
    { name: "표고버섯", status: "green", keywords: ["버섯", "야채"], desc: "감칠맛 및 비타민D 풍부. 기둥 떼고 갓만 사용." },
    { name: "양송이버섯", status: "green", keywords: ["버섯", "야채"], desc: "부드러운 식감. 중기부터 잘 먹는 버섯." },
    { name: "팽이버섯", status: "green", keywords: ["버섯", "야채"], desc: "잘게 다지지 않으면 변으로 그대로 나옵니다." },
    { name: "새송이버섯", status: "green", keywords: ["버섯", "야채"], desc: "쫄깃하므로 아주 얇게 다져서 급여하세요." },

    // 🟢 안심 - 과일, 유제품, 기타
    { name: "사과", status: "green", keywords: ["과일"], desc: "생과일은 질식 위험(퓨레나 찌기)." },
    { name: "배", status: "green", keywords: ["과일"], desc: "감기 예방. 곱게 갈아서 급여." },
    { name: "바나나", status: "green", keywords: ["과일"], desc: "검은 반점이 생긴 푹 익은 것만 급여(변비 예방)." },
    { name: "수박", status: "green", keywords: ["과일"], desc: "씨 완벽히 빼고 과육만." },
    { name: "멜론", status: "green", keywords: ["과일"], desc: "부드럽고 달콤함. 과육만 으깨서 급여." },
    { name: "참외", status: "green", keywords: ["과일"], desc: "씨와 태좌(가운데 흰부분)를 완전히 긁어내고 과육만 갈아주세요." },
    { name: "블루베리", status: "green", keywords: ["베리", "과일"], desc: "중기부터 껍질째 갈거나 후기엔 반으로 잘라 급여." },
    { name: "아보카도", status: "green", keywords: ["지방", "과카몰리"], desc: "건강한 지방. 까맣게 후숙된 것을 으깨주세요." },
    { name: "자두", status: "green", keywords: ["푸룬", "과일"], desc: "변비 직빵. 씨 완벽 제거." },
    { name: "망고", status: "green", keywords: ["열대과일", "과일"], desc: "옻나무과 교차 알레르기 주의. 돌 이후 부드러운 과육만." },
    { name: "계란노른자", status: "green", keywords: ["달걀", "알", "노른자"], desc: "철분 보충제. 완숙으로 푹 삶아 으깨주세요." },
    { name: "미역", status: "green", keywords: ["해조류", "다시마", "김"], desc: "짠기 완벽히 빼고 다지세요. (김은 무조미 김 사용)" },
    { name: "김", status: "green", keywords: ["해조류", "돌김", "김가루"], desc: "중기/후기부터 조미되지 않은 순수 생김을 구워 부숴주세요." },
    { name: "치즈", status: "green", keywords: ["아기치즈", "유제품"], desc: "1단계 아기치즈로 간식이나 밥에 녹여주세요." },
    { name: "요거트", status: "green", keywords: ["요플레", "그릭요거트", "유제품"], desc: "무가당 100% 플레인 요거트만 중/후기 급여." },
    { name: "무염버터", status: "green", keywords: ["지방", "유제품"], desc: "풍미와 체중 증량을 위해 볶음 요리 시 소량 사용." },
    { name: "현미유", status: "green", keywords: ["기름", "식용유", "올리브유", "참기름"], desc: "이유식 볶음 요리 시 가장 무난하고 안전한 기름입니다." },
];

// 🍲 2. 안심 레시피 데이터 (총 70종 - 매일매일 다른 식단! 다양성 극대화)
const babyFoodData = [
    // ---------------- [초기 이유식: 4~6개월] - 미음, 퓨레 (15종) ----------------
    { id: "e01", name: "소고기 미음", age: "early", goal: "iron", allergens: [], desc: "가장 기본 첫 철분 보충식", texture: "10배 미음", ingredients: "소고기 안심 10g, 불린 쌀(쌀가루) 15g", recipe: ["1. 소고기 핏물 빼고 푹 삶기", "2. 믹서에 곱게 갈기", "3. 쌀가루와 끓여 체에 거르기"] },
    { id: "e02", name: "소고기 청경채 미음", age: "early", goal: "iron", allergens: [], desc: "비타민C와 소고기의 완벽 궁합", texture: "미음", ingredients: "소고기 10g, 청경채 10g, 쌀가루 15g", recipe: ["1. 핏물 뺀 소고기와 청경채 잎 데치기", "2. 갈아서 쌀가루와 끓이고 체에 거르기"] },
    { id: "e03", name: "소고기 비타민 미음", age: "early", goal: "iron", allergens: [], desc: "빈혈 예방에 특효", texture: "미음", ingredients: "소고기 10g, 비타민(다채) 10g, 쌀가루 15g", recipe: ["1. 고기 삶고 비타민 잎 데치기", "2. 갈아서 끓이기"] },
    { id: "e04", name: "소고기 양배추 미음", age: "early", goal: "poop", allergens: [], desc: "달큰한 맛과 장 활동 촉진", texture: "미음", ingredients: "소고기 10g, 양배추 10g, 쌀가루 15g", recipe: ["1. 양배추 심지 빼고 잎만 찌기", "2. 삶은 고기와 갈아서 끓이기"] },
    { id: "e05", name: "소고기 애호박 미음", age: "early", goal: "all", allergens: [], desc: "위장을 편안하게", texture: "미음", ingredients: "소고기 10g, 애호박 10g, 쌀가루 15g", recipe: ["1. 애호박 씨/껍질 제거 후 찌기", "2. 삶은 고기와 갈아서 끓이기"] },
    { id: "e06", name: "소고기 브로콜리 미음", age: "early", goal: "iron", allergens: [], desc: "면역력 쑥쑥", texture: "미음", ingredients: "소고기 10g, 브로콜리 꽃송이 10g, 쌀가루 15g", recipe: ["1. 브로콜리 꽃송이 데치기", "2. 고기와 끓이기"] },
    { id: "e07", name: "닭고기 미음", age: "early", goal: "weight", allergens: [], desc: "소고기 다음으로 담백한 단백질", texture: "미음", ingredients: "닭안심 10g, 쌀가루 15g", recipe: ["1. 닭안심 힘줄/막 제거 후 푹 삶기", "2. 갈아서 끓이기"] },
    { id: "e08", name: "닭고기 고구마 미음", age: "early", goal: "weight", allergens: [], desc: "단맛으로 정체기 극복", texture: "미음", ingredients: "닭안심 10g, 고구마 10g, 쌀가루 15g", recipe: ["1. 닭 삶고 고구마 찌기", "2. 갈아서 끓이기"] },
    { id: "e09", name: "오트밀 사과 미음", age: "early", goal: "poop", allergens: [], desc: "변비 직빵 아침 메뉴", texture: "미음", ingredients: "오트밀가루 10g, 사과 10g, 쌀가루 10g", recipe: ["1. 사과 강판에 갈기", "2. 가루 물에 풀어 다 같이 끓이기"] },
    { id: "e10", name: "단호박 퓨레", age: "early", goal: "weight", allergens: [], desc: "달콤 부드러운 간식", texture: "퓨레", ingredients: "단호박 1/4개", recipe: ["1. 껍질/씨 빼고 푹 찌기", "2. 따뜻할 때 포크로 으깨기"] },
    { id: "e11", name: "고구마 사과 퓨레", age: "early", goal: "poop", allergens: [], desc: "최고의 쾌변 간식", texture: "퓨레", ingredients: "고구마 1/2개, 사과 1/4개", recipe: ["1. 고구마 찌기", "2. 사과 갈아서 섞기"] },
    { id: "e12", name: "감자 퓨레", age: "early", goal: "weight", allergens: [], desc: "포만감 좋은 간식", texture: "퓨레", ingredients: "감자 1개", recipe: ["1. 싹 완벽 제거 후 찌기", "2. 분유물로 농도 맞추며 으깨기"] },
    { id: "e13", name: "자두 바나나 퓨레", age: "early", goal: "poop", allergens: [], desc: "악성 변비 응급처방", texture: "퓨레", ingredients: "푹 익은 바나나 1/2개, 자두 1T", recipe: ["1. 바나나 으깨기", "2. 자두 씨/껍질 까서 섞기"] },
    { id: "e14", name: "비트 사과 미음", age: "early", goal: "poop", allergens: [], desc: "예쁜 핑크빛 항산화 미음", texture: "미음", ingredients: "비트 5g, 사과 10g, 쌀가루 15g", recipe: ["1. 비트 껍질 까고 푹 찌기", "2. 사과 갈아서 쌀가루와 끓이기"] },
    { id: "e15", name: "단호박 아보카도 퓨레", age: "early", goal: "weight", allergens: [], desc: "고열량 프리미엄 퓨레", texture: "퓨레", ingredients: "단호박 20g, 후숙 아보카도 10g", recipe: ["1. 단호박 찌기", "2. 아보카도 파내어 섞어 으깨기"] },

    // ---------------- [중기 이유식: 7~9개월] - 다양한 7배죽 (20종) ----------------
    { id: "m01", name: "소고기 브로콜리 죽", age: "mid", goal: "iron", allergens: [], desc: "철분 폭탄의 정석 조합", texture: "쌀알 1/2 (7배죽)", ingredients: "소고기 20g, 브로콜리 15g, 불린쌀 25g", recipe: ["1. 소고기 삶아 다지기", "2. 브로콜리 다지기", "3. 고기 육수에 푹 끓이기"] },
    { id: "m02", name: "소고기 표고버섯 죽", age: "mid", goal: "all", allergens: [], desc: "버섯 감칠맛 영양죽", texture: "입자 있는 죽", ingredients: "소고기 20g, 표고버섯 10g, 불린쌀 25g", recipe: ["1. 소고기, 표고버섯 데쳐 3mm 다지기", "2. 육수에 끓이기"] },
    { id: "m03", name: "소고기 양배추 사과 죽", age: "mid", goal: "poop", allergens: [], desc: "장 활동 촉진 달콤 레시피", texture: "죽", ingredients: "소고기 20g, 양배추 10g, 사과 10g, 쌀 25g", recipe: ["1. 고기/양배추 다지기", "2. 육수에 끓이다 마지막에 다진 사과 넣기"] },
    { id: "m04", name: "닭고기 고구마 당근 죽", age: "mid", goal: "weight", allergens: [], desc: "달콤 든든 체중 쑥쑥", texture: "죽", ingredients: "닭안심 20g, 고구마 15g, 당근 10g, 쌀 25g", recipe: ["1. 닭 삶아 다지기", "2. 고구마 으깨고 당근 다져 끓이기"] },
    { id: "m05", name: "닭고기 시금치 당근 죽", age: "mid", goal: "iron", allergens: [], desc: "철분/단백질 밸런스", texture: "죽", ingredients: "닭안심 20g, 시금치 10g, 당근 10g, 쌀 25g", recipe: ["1. 닭고기/당근 다지기", "2. 시금치 데쳐 다지고 끓이기"] },
    { id: "m06", name: "두부 시금치 노른자 죽", age: "mid", goal: "iron", allergens: ["egg", "soy"], desc: "고기 없는 식물성 철분 특식", texture: "묽은 죽", ingredients: "두부 15g, 시금치 10g, 계란노른자 1개, 쌀 25g", recipe: ["1. 노른자 삶아 으깨기", "2. 시금치/두부 다져서 끓이기"] },
    { id: "m07", name: "대구살 무 당근 죽", age: "mid", goal: "all", allergens: ["seafood"], desc: "소화 잘되는 시원한 죽", texture: "죽", ingredients: "대구살 20g, 무 15g, 당근 10g, 쌀 25g", recipe: ["1. 대구 쪄서 가시 제거", "2. 무/당근 다져 채수에 끓이기"] },
    { id: "m08", name: "가자미살 애호박 죽", age: "mid", goal: "weight", allergens: ["seafood"], desc: "고소한 오메가3 죽", texture: "죽", ingredients: "가자미 20g, 애호박 15g, 쌀 25g", recipe: ["1. 가자미 쪄서 가시 제거", "2. 애호박 다져서 끓이기"] },
    { id: "m09", name: "검은콩 소고기 죽", age: "mid", goal: "weight", allergens: ["soy"], desc: "고소함 폭발 식물성 단백질", texture: "죽", ingredients: "검은콩 10g, 소고기 20g, 쌀 25g", recipe: ["1. 검은콩 불려 껍질 까고 푹 삶아 으깨기", "2. 고기와 끓이기"] },
    { id: "m10", name: "소고기 콜리플라워 죽", age: "mid", goal: "iron", allergens: [], desc: "부드럽고 소화 잘되는 하얀 죽", texture: "죽", ingredients: "소고기 20g, 콜리플라워 15g, 쌀 25g", recipe: ["1. 콜리플라워 꽃송이 다지기", "2. 고기와 끓이기"] },
    { id: "m11", name: "닭고기 양송이버섯 죽", age: "mid", goal: "weight", allergens: [], desc: "부드러운 식감의 조화", texture: "죽", ingredients: "닭안심 20g, 양송이 15g, 쌀 25g", recipe: ["1. 양송이 껍질 벗겨 다지기", "2. 닭고기와 끓이기"] },
    { id: "m12", name: "소고기 비타민 고구마 죽", age: "mid", goal: "iron", allergens: [], desc: "철분 듬뿍에 달콤함 추가", texture: "죽", ingredients: "소고기 20g, 비타민 10g, 고구마 10g, 쌀 25g", recipe: ["1. 비타민 잎 데쳐 다지기", "2. 고구마 으깨어 끓이기"] },
    { id: "m13", name: "소고기 무 미역 죽", age: "mid", goal: "poop", allergens: [], desc: "변비 부드럽게 해결", texture: "죽", ingredients: "소고기 20g, 불린 미역 10g, 무 10g, 쌀 25g", recipe: ["1. 미역 짠기 빼고 아주 잘게 다지기", "2. 무 다져 고기와 끓이기"] },
    { id: "m14", name: "계란 노른자 감자 죽", age: "mid", goal: "all", allergens: ["egg"], desc: "고소한 아침 대용", texture: "죽", ingredients: "계란노른자 1개, 감자 20g, 쌀 25g", recipe: ["1. 노른자 으깨기", "2. 감자 다져 끓이다 마지막에 노른자 섞기"] },
    { id: "m15", name: "소고기 비트 퀴노아 죽", age: "mid", goal: "iron", allergens: [], desc: "퀴노아가 톡톡 터지는 식감", texture: "죽", ingredients: "소고기 20g, 비트 10g, 불린 퀴노아 10g, 쌀 15g", recipe: ["1. 비트 쪄서 다지기", "2. 소고기와 퀴노아 넣어 푹 끓이기"] },
    { id: "m16", name: "닭고기 아스파라거스 죽", age: "mid", goal: "all", allergens: [], desc: "깔끔하고 담백한 영양죽", texture: "죽", ingredients: "닭안심 20g, 아스파라거스 15g, 쌀 25g", recipe: ["1. 아스파라거스 껍질 벗겨 데쳐 다지기", "2. 끓이기"] },
    { id: "m17", name: "병아리콩 고구마 죽", age: "mid", goal: "weight", allergens: ["soy"], desc: "밤처럼 고소하게 살찌우기", texture: "크리미한 죽", ingredients: "병아리콩 10g, 고구마 15g, 쌀 20g", recipe: ["1. 병아리콩 불려 껍질 까고 삶기", "2. 고구마 으깨어 같이 끓이기"] },
    { id: "m18", name: "연어 브로콜리 타락죽", age: "mid", goal: "weight", allergens: ["seafood", "dairy"], desc: "분유물로 만든 크림수프 느낌", texture: "크림 수프", ingredients: "연어 20g, 브로콜리 15g, 쌀 25g, 조제분유물 50ml", recipe: ["1. 연어 쪄서 으깨기", "2. 브로콜리 다져 끓이다 분유물 넣기"] },
    { id: "m19", name: "소고기 연근 당근 죽", age: "mid", goal: "poop", allergens: [], desc: "장 튼튼 연근 영양죽", texture: "죽", ingredients: "소고기 20g, 연근 10g, 당근 10g, 쌀 25g", recipe: ["1. 연근 식초물에 데쳐 아주 잘게 다지기", "2. 고기/당근과 끓이기"] },
    { id: "m20", name: "닭고기 렌틸콩 단호박 죽", age: "mid", goal: "weight", allergens: [], desc: "고단백 달콤 영양죽", texture: "죽", ingredients: "닭안심 20g, 레드렌틸콩 10g, 단호박 15g, 쌀 20g", recipe: ["1. 렌틸콩 불려 삶기", "2. 단호박 으깨어 닭고기와 끓이기"] },

    // ---------------- [후기 이유식: 10~11개월] - 진밥, 무른밥 (20종) ----------------
    { id: "l01", name: "소고기 가지 진밥", age: "late", goal: "weight", allergens: [], desc: "물컹 식감 적응 덮밥 느낌", texture: "진밥(4배죽)", ingredients: "소고기 30g, 가지 20g, 양파 10g, 진밥 50g", recipe: ["1. 가지 껍질 벗겨 다지기", "2. 소고기 볶다 진밥 넣고 채수로 졸이기"] },
    { id: "l02", name: "소고기 팽이버섯 두부 진밥", age: "late", goal: "weight", allergens: ["soy"], desc: "단백질 끝판왕 식감 밥", texture: "진밥", ingredients: "소고기 30g, 팽이버섯 10g, 두부 15g, 진밥 50g", recipe: ["1. 팽이버섯 아주 잘게 다지기", "2. 고기 볶다 밥/두부 넣고 끓이기"] },
    { id: "l03", name: "닭고기 단호박 양배추 진밥", age: "late", goal: "poop", allergens: [], desc: "마시듯 먹는 달콤 진밥", texture: "진밥", ingredients: "닭안심 30g, 단호박 20g, 양배추 15g, 진밥 50g", recipe: ["1. 단호박 쪄 으깨기", "2. 닭/양배추 볶아 육수에 졸이기"] },
    { id: "l04", name: "흰살생선 치즈 진밥", age: "late", goal: "all", allergens: ["dairy", "seafood"], desc: "정체기 박살 짭짤고소 치즈 특식", texture: "진밥", ingredients: "대구살 30g, 아기치즈 1/2장, 애호박 15g, 진밥 50g", recipe: ["1. 대구 쪄서 가시 제거", "2. 밥 넣고 끓이다 치즈 녹여 비비기"] },
    { id: "l05", name: "새우 양송이 볶음 진밥", age: "late", goal: "weight", allergens: ["shellfish"], desc: "탱글한 해산물 볶음밥 느낌", texture: "볶음진밥", ingredients: "새우살 20g, 양송이 15g, 양파 10g, 진밥 50g", recipe: ["1. 새우 데쳐 다지기", "2. 야채 현미유 볶다 진밥 넣고 촉촉히 볶기"] },
    { id: "l06", name: "소고기 땅콩 잣 진밥", age: "late", goal: "weight", allergens: ["peanut"], desc: "고열량 보양식. 견과류 테스트 후 급여!", texture: "진밥", ingredients: "소고기 30g, 땅콩가루 1t, 잣가루 1t, 진밥 50g", recipe: ["1. 소고기 다져 볶기", "2. 밥 끓이다 땅콩/잣가루 뿌려 섞기"] },
    { id: "l07", name: "토마토 달걀 볶음 진밥", age: "late", goal: "iron", allergens: ["egg"], desc: "상큼한 영양 밸런스 밥", texture: "무른 볶음밥", ingredients: "방울토마토 3개, 계란 1개, 진밥 50g", recipe: ["1. 토마토 껍질 벗겨 다지기", "2. 계란 스크램블 해 밥과 볶기"] },
    { id: "l08", name: "아보카도 소고기 비빔밥", age: "late", goal: "weight", allergens: [], desc: "건강한 지방 슈퍼푸드 비빔밥", texture: "꾸덕한 밥", ingredients: "후숙 아보카도 1/4개, 볶은 소고기 20g, 진밥 50g", recipe: ["1. 고기 볶아 다지기", "2. 아보카도 으깨서 따뜻한 밥에 비비기"] },
    { id: "l09", name: "연어 감자 양파 진밥", age: "late", goal: "weight", allergens: ["seafood"], desc: "두뇌 발달 오메가3 폭탄 특식", texture: "진밥", ingredients: "연어 20g, 감자 15g, 양파 10g, 진밥 50g", recipe: ["1. 연어 쪄서 으깨기", "2. 감자/양파 다져 볶다 진밥과 끓이기"] },
    { id: "l10", name: "닭고기 밤 대추 진밥", age: "late", goal: "all", allergens: [], desc: "면역력 높여주는 가을/겨울 영양밥", texture: "진밥", ingredients: "닭안심 30g, 찐 밤 15g, 대추 1알(씨 제거), 진밥 50g", recipe: ["1. 닭 다지기", "2. 밤/대추 속살 으깨어 닭육수에 졸이기"] },
    { id: "l11", name: "전복 미역 진밥", age: "late", goal: "weight", allergens: ["seafood"], desc: "아기 몸보신 프리미엄 덮밥", texture: "진밥", ingredients: "전복살 20g, 불린 미역 10g, 무 10g, 진밥 50g", recipe: ["1. 전복 내장 빼고 쪄서 얇게 다지기", "2. 미역 다져 밥과 졸이기"] },
    { id: "l12", name: "돼지고기 사과 덮밥", age: "late", goal: "weight", allergens: [], desc: "달콤 소화 촉진 돼지고기 밥", texture: "진밥", ingredients: "돼지안심 30g, 사과 20g, 양파 10g, 진밥 50g", recipe: ["1. 고기 아주 잘게 다져 양파와 볶기", "2. 사과 다져 밥과 끓이기"] },
    { id: "l13", name: "게살 연근 진밥", age: "late", goal: "poop", allergens: ["shellfish"], desc: "아삭 짭조름 식감 천재", texture: "진밥", ingredients: "크래미 20g, 연근 10g, 당근 10g, 진밥 50g", recipe: ["1. 연근 데쳐 아주 잘게 다지기", "2. 게살 찢어 볶다 밥과 섞기"] },
    { id: "l14", name: "토마토 가지 소고기 리조또", age: "late", goal: "iron", allergens: ["dairy"], desc: "서양식 리조또의 깊은 풍미", texture: "리조또", ingredients: "토마토 3개, 가지 15g, 소고기 30g, 아기치즈 1장, 진밥 50g", recipe: ["1. 토마토 껍질 까고 다지기", "2. 고기 볶다 밥 넣고 마지막 치즈 녹이기"] },
    { id: "l15", name: "소고기 콩나물 무 진밥", age: "late", goal: "all", allergens: [], desc: "시원한 아기 해장국 느낌", texture: "진밥", ingredients: "소고기 30g, 콩나물 15g, 무 15g, 진밥 50g", recipe: ["1. 콩나물 머리/꼬리 떼고 다지기", "2. 볶다가 밥 넣고 끓이기"] },
    { id: "l16", name: "닭고기 파프리카 진밥", age: "late", goal: "all", allergens: [], desc: "비타민C 풍부 색감 예쁜 밥", texture: "진밥", ingredients: "닭안심 30g, 파프리카 15g, 양파 10g, 진밥 50g", recipe: ["1. 파프리카 껍질 벗겨 다지기", "2. 고기와 볶다 밥 넣기"] },
    { id: "l17", name: "소고기 무 미역 진밥", age: "late", goal: "poop", allergens: [], desc: "배변 돕는 전통 영양식", texture: "국물 자박한 밥", ingredients: "소고기 30g, 미역 10g, 무 10g, 진밥 50g", recipe: ["1. 미역 아주 잘게 다지기", "2. 고기 볶다 밥 넣고 졸이기"] },
    { id: "l18", name: "닭고기 오트밀 사과 진밥", age: "late", goal: "poop", allergens: [], desc: "식이섬유 듬뿍 장 청소 밥", texture: "진밥", ingredients: "닭안심 20g, 퀵오트밀 10g, 사과 15g, 진밥 40g", recipe: ["1. 사과 다지기", "2. 고기 볶다 오트밀/밥/사과 넣고 물 끓이기"] },
    { id: "l19", name: "관자 브로콜리 양파 진밥", age: "late", goal: "weight", allergens: ["seafood"], desc: "부드럽고 단맛 나는 고급 해산물 밥", texture: "진밥", ingredients: "관자 20g, 브로콜리 15g, 양파 10g, 진밥 50g", recipe: ["1. 관자 푹 익혀 아주 잘게 다지기", "2. 야채 볶다 밥과 졸이기"] },
    { id: "l20", name: "소고기 팽이버섯 부추 진밥", age: "late", goal: "iron", allergens: [], desc: "향긋한 부추로 입맛 돋우는 밥", texture: "진밥", ingredients: "소고기 30g, 팽이버섯 10g, 부추 5g, 진밥 50g", recipe: ["1. 팽이버섯/부추 아주 잘게 다지기", "2. 고기 볶다 밥과 끓이기"] },

    // ---------------- [완료기 유아식: 12개월 이상] - 유아반찬, 면, 베이킹 (15종) ----------------
    { id: "d01", name: "소고기 야채 미트볼", age: "done", goal: "iron", allergens: ["egg", "flour"], desc: "손으로 잡고 먹는 BLW 필수 반찬", texture: "고기 완자", ingredients: "다진 소고기 50g, 당근/양파 20g, 계란 1/2개, 전분 1T", recipe: ["1. 고기 야채 볼에 담고 계란/전분 섞기", "2. 동그랗게 빚어 찜기에 15분 찌기"] },
    { id: "d02", name: "순한맛 아기 카레", age: "done", goal: "weight", allergens: ["dairy", "flour"], desc: "야채 안 먹는 아이 마법의 덮밥 소스", texture: "덮밥", ingredients: "아기용 카레가루 1T, 소고기 20g, 감자/당근 15g, 밥", recipe: ["1. 고기 야채 깍둑썰어 볶기", "2. 물 붓고 카레가루 풀어 농도 맞추기"] },
    { id: "d03", name: "무염 아기 간장 찜닭", age: "done", goal: "all", allergens: ["soy", "flour"], desc: "단짠 신세계 사과즙 찜닭", texture: "찢어지는 고기", ingredients: "닭다리살 50g, 고구마 20g, 아기간장 1t, 사과즙 2T", recipe: ["1. 닭 자르기", "2. 간장/사과즙 마리네이드", "3. 고구마 넣고 물 부어 푹 졸이기"] },
    { id: "d04", name: "시금치 프리타타", age: "done", goal: "iron", allergens: ["egg", "dairy"], desc: "푸딩처럼 부드러운 계란찜", texture: "푸딩", ingredients: "계란 1개, 시금치 15g, 아기치즈 1/2장, 우유 2T", recipe: ["1. 볼에 계란, 우유, 치즈, 다진 시금치 섞기", "2. 내열용기에 담아 찜기에 10분 찌기"] },
    { id: "d05", name: "잔멸치 호두 주먹밥", age: "done", goal: "weight", allergens: ["seafood", "peanut"], desc: "칼슘 폭탄 외출용 주먹밥", texture: "주먹밥", ingredients: "지리멸치 10g, 호두가루 1t, 김가루, 밥 70g", recipe: ["1. 멸치 데쳐 짠기 빼고 마른팬에 볶기", "2. 밥에 재료 섞어 동그랗게 빚기"] },
    { id: "d06", name: "대구살 야채 전", age: "done", goal: "all", allergens: ["seafood", "egg", "flour"], desc: "기름 고소한 맛 흰살생선 핑거푸드", texture: "생선전", ingredients: "대구살 30g, 애호박 10g, 계란물, 부침가루", recipe: ["1. 대구살 으깨 다진야채/가루/계란물 섞기", "2. 기름 두른 팬에 작게 부치기"] },
    { id: "d07", name: "소고기 밥머핀", age: "done", goal: "weight", allergens: ["egg", "flour"], desc: "빵처럼 들고 먹는 고기밥", texture: "촉촉한 머핀", ingredients: "다진 소고기 20g, 야채 20g, 밥 30g, 계란 1개", recipe: ["1. 고기/야채 볶아 밥/계란 섞기", "2. 머핀 틀에 담아 오븐/에프 15분 굽기"] },
    { id: "d08", name: "들깨 무나물 볶음밥", age: "done", goal: "poop", allergens: [], desc: "고소하고 소화 잘되는 밥", texture: "볶음밥", ingredients: "무 30g, 소고기 20g, 들깨가루 1t, 밥 70g", recipe: ["1. 무 채 썰어 고기와 볶기", "2. 밥 넣고 볶다 들깨가루 섞기"] },
    { id: "d09", name: "렌틸콩 토마토 파스타", age: "done", goal: "iron", allergens: ["flour"], desc: "비주얼 폭발 아기 파스타 특식", texture: "면 요리", ingredients: "레드렌틸콩 15g, 토마토 1/2개, 소고기 30g, 아기면 50g", recipe: ["1. 렌틸콩 삶고 토마토 갈기", "2. 고기 볶다 소스 넣고 끓여 삶은 면 비비기"] },
    { id: "d10", name: "새우 두부 완자", age: "done", goal: "weight", allergens: ["shellfish", "soy", "egg", "flour"], desc: "고소하고 탱글한 반찬", texture: "완자", ingredients: "새우살 40g, 두부 30g, 양파 10g, 전분 1T, 계란 1/2개", recipe: ["1. 새우, 으깬 두부, 전분, 계란 치대기", "2. 빚어서 찜기에 15분 찌기"] },
    { id: "d11", name: "블루베리 오트밀 팬케이크", age: "done", goal: "poop", allergens: ["egg", "dairy", "flour"], desc: "무설탕 달콤 아침 팬케이크", texture: "촉촉한 빵", ingredients: "블루베리 10알, 오트밀가루 30g, 바나나 1/2개, 계란 1개, 우유 2T", recipe: ["1. 바나나 으깨 계란/우유/가루 섞기", "2. 반 자른 블루베리 넣고 팬에 굽기"] },
    { id: "d12", name: "치즈 감자 고로케", age: "done", goal: "weight", allergens: ["dairy", "egg", "flour"], desc: "에어프라이어 겉바속촉 간식", texture: "크로켓", ingredients: "감자 1개, 아기치즈 1장, 계란물, 빵가루", recipe: ["1. 감자 쪄서 으깨기", "2. 치즈 넣고 빚어 계란/빵가루 묻혀 에프 10분"] },
    { id: "d13", name: "전복 버터 구이 덮밥", age: "done", goal: "weight", allergens: ["seafood", "dairy"], desc: "버터 풍미 기가 막힌 돌 특식", texture: "덮밥", ingredients: "전복살 30g, 무염버터 1t, 양파 10g, 밥 70g", recipe: ["1. 전복 얇게 저미기", "2. 버터에 양파/전복 노릇하게 구워 밥에 올리기"] },
    { id: "d14", name: "소고기 숙주 볶음", age: "done", goal: "all", allergens: ["soy"], desc: "아삭한 식감 적응용 반찬", texture: "부드러운 볶음", ingredients: "소고기 30g, 숙주 20g, 대파 약간, 아기간장 1t", recipe: ["1. 숙주 데쳐 잘게 썰기", "2. 고기 볶다 숙주/간장 넣어 빠르게 볶기"] },
    { id: "d15", name: "두부 스테이크", age: "done", goal: "weight", allergens: ["soy", "egg", "flour"], desc: "고기 안 먹는 아이를 위한 고단백 스테이크", texture: "부드러운 패티", ingredients: "물기 짠 두부 50g, 다진 야채 20g, 빵가루 1T, 계란 1/2개", recipe: ["1. 두부와 야채, 계란, 빵가루 치대기", "2. 도톰하게 빚어 기름 두른 팬에 굽기"] },


// ---------------- [공장장 1차 추가분: 초기 이유식 10종] ----------------
    { id: "e16", name: "소고기 감자 미음", age: "early", goal: "iron", allergens: [], desc: "고소한 감자로 소고기 특유의 향을 완벽히 잡은 미음", texture: "10배 미음", ingredients: "소고기 10g, 감자 10g, 쌀가루 15g", recipe: ["1. 핏물 뺀 소고기 푹 삶기", "2. 감자 싹 완벽히 도려내고 찌기", "3. 믹서에 갈아 끓이기"] },
    { id: "e17", name: "소고기 무 미음", age: "early", goal: "iron", allergens: [], desc: "천연 소화제 무가 들어가 속이 편안한 첫 고기 미음", texture: "10배 미음", ingredients: "소고기 10g, 무 10g, 쌀가루 15g", recipe: ["1. 소고기와 무를 끓는 물에 푹 익히기", "2. 갈아서 쌀가루와 끓이기"] },
    { id: "e18", name: "닭고기 청경채 미음", age: "early", goal: "weight", allergens: [], desc: "소화 잘되는 닭안심과 비타민의 만남", texture: "10배 미음", ingredients: "닭안심 10g, 청경채 10g, 쌀가루 15g", recipe: ["1. 닭안심 힘줄 제거 후 삶기", "2. 청경채 잎 데치기", "3. 갈아서 끓이기"] },
    { id: "e19", name: "닭고기 감자 미음", age: "early", goal: "weight", allergens: [], desc: "포만감이 좋아 수면 의식 전에 먹이기 좋은 미음", texture: "10배 미음", ingredients: "닭안심 10g, 감자 10g, 쌀가루 15g", recipe: ["1. 닭고기 삶고 감자 찌기", "2. 쌀미음과 함께 갈아 끓이기"] },
    { id: "e20", name: "단호박 오이 미음", age: "early", goal: "all", allergens: [], desc: "열이 많거나 수분 보충이 필요할 때 좋은 쿨링 미음", texture: "주르륵 흐르는 미음", ingredients: "단호박 10g, 오이 10g, 쌀가루 15g", recipe: ["1. 오이는 씨/껍질 빼기", "2. 단호박 찌고 오이와 함께 갈아 끓이기"] },
    { id: "e21", name: "애호박 퓨레", age: "early", goal: "poop", allergens: [], desc: "달큰하고 소화가 매우 잘되는 채소 간식", texture: "부드러운 퓨레", ingredients: "애호박 1/2개", recipe: ["1. 애호박 껍질과 씨를 도려내고 푹 찌기", "2. 따뜻할 때 곱게 으깨기"] },
    { id: "e22", name: "브로콜리 사과 퓨레", age: "early", goal: "all", allergens: [], desc: "브로콜리 거부감을 사과의 단맛으로 잡은 간식", texture: "부드러운 퓨레", ingredients: "브로콜리 꽃송이 15g, 사과 1/4개", recipe: ["1. 브로콜리 데치기", "2. 사과 갈아서 브로콜리와 함께 믹서에 갈기"] },
    { id: "e23", name: "배 퓨레", age: "early", goal: "poop", allergens: [], desc: "감기 기운이 있거나 기침할 때 먹이는 천연 상비약", texture: "수분감 많은 퓨레", ingredients: "배 1/4개", recipe: ["1. 배 껍질을 깎고 강판에 갈기", "2. 냄비에 살짝 데워 따뜻하게 급여"] },
    { id: "e24", name: "청경채 배 미음", age: "early", goal: "poop", allergens: [], desc: "시원한 배즙이 들어가 변을 무르게 해주는 미음", texture: "주르륵 흐르는 미음", ingredients: "청경채 10g, 배 10g, 쌀가루 15g", recipe: ["1. 청경채 잎 데치고 배 갈기", "2. 쌀가루와 섞어 끓이기"] },
    { id: "e25", name: "비트 감자 미음", age: "early", goal: "poop", allergens: [], desc: "시각적 호기심을 자극하는 핑크빛 포만감 미음", texture: "10배 미음", ingredients: "비트 5g, 감자 10g, 쌀가루 15g", recipe: ["1. 비트와 감자 껍질 까고 푹 찌기", "2. 갈아서 끓이기"] },

    // ---------------- [공장장 1차 추가분: 중기 이유식 15종] ----------------
    { id: "m21", name: "소고기 가지 죽", age: "mid", goal: "iron", allergens: [], desc: "안토시아닌이 풍부! 가지의 물컹한 식감에 적응하는 죽", texture: "7배죽", ingredients: "소고기 20g, 가지 15g, 쌀 25g", recipe: ["1. 가지 껍질 벗겨 다지기", "2. 소고기 다져 푹 끓이기"] },
    { id: "m22", name: "소고기 양파 죽", age: "mid", goal: "iron", allergens: [], desc: "양파의 단맛이 고기 누린내를 완벽히 잡아주는 죽", texture: "7배죽", ingredients: "소고기 20g, 양파 10g, 쌀 25g", recipe: ["1. 양파 매운맛이 날아가도록 물에 담가두기", "2. 고기와 양파 다져 푹 끓이기"] },
    { id: "m23", name: "소고기 배추 죽", age: "mid", goal: "iron", allergens: [], desc: "알배기 배추의 시원하고 달콤한 맛이 일품", texture: "7배죽", ingredients: "소고기 20g, 배추잎 15g, 쌀 25g", recipe: ["1. 배추의 부드러운 잎부분만 다지기", "2. 고기와 육수에 끓이기"] },
    { id: "m24", name: "소고기 무 당근 죽", age: "mid", goal: "iron", allergens: [], desc: "천연 소화제 무와 비타민A 당근의 영양 밸런스", texture: "7배죽", ingredients: "소고기 20g, 무 10g, 당근 10g, 쌀 25g", recipe: ["1. 무와 당근 다지기", "2. 소고기 육수에 푹 끓이기"] },
    { id: "m25", name: "닭고기 연근 죽", age: "mid", goal: "weight", allergens: [], desc: "설사할 때 특효약! 연근의 아삭함이 남은 보양죽", texture: "7배죽", ingredients: "닭안심 20g, 연근 10g, 쌀 25g", recipe: ["1. 연근 식초물 데쳐 떫은맛 빼고 다지기", "2. 닭고기와 끓이기"] },
    { id: "m26", name: "닭고기 비트 죽", age: "mid", goal: "weight", allergens: [], desc: "면역력을 높여주는 예쁜 붉은색 닭죽", texture: "7배죽", ingredients: "닭안심 20g, 비트 10g, 쌀 25g", recipe: ["1. 비트 쪄서 다지기", "2. 닭고기 육수에 끓이기"] },
    { id: "m27", name: "닭고기 배추 죽", age: "mid", goal: "weight", allergens: [], desc: "소화기가 약한 아기를 위한 가장 순하고 부드러운 죽", texture: "7배죽", ingredients: "닭안심 20g, 배추 15g, 쌀 25g", recipe: ["1. 닭고기 삶아 다지기", "2. 배추 잎 다져 끓이기"] },
    { id: "m28", name: "대구살 양배추 죽", age: "mid", goal: "all", allergens: ["seafood"], desc: "흰살생선 특유의 담백함과 양배추의 단맛이 만난 죽", texture: "7배죽", ingredients: "대구살 20g, 양배추 15g, 쌀 25g", recipe: ["1. 대구살 가시 제거하여 찌기", "2. 양배추 다져 끓이기"] },
    { id: "m29", name: "대구살 고구마 죽", age: "mid", goal: "poop", allergens: ["seafood"], desc: "생선 안 먹는 아이 입맛을 고구마로 싹 돌리는 마법의 죽", texture: "7배죽", ingredients: "대구살 20g, 고구마 15g, 쌀 25g", recipe: ["1. 대구살 가시 제거", "2. 고구마 으깨고 생선살과 끓이기"] },
    { id: "m30", name: "가자미 브로콜리 죽", age: "mid", goal: "weight", allergens: ["seafood"], desc: "오메가3와 비타민이 가득한 든든한 한 끼", texture: "7배죽", ingredients: "가자미 20g, 브로콜리 15g, 쌀 25g", recipe: ["1. 가자미 쪄서 가시 제거", "2. 브로콜리 다져 끓이기"] },
    { id: "m31", name: "노른자 고구마 죽", age: "mid", goal: "weight", allergens: ["egg"], desc: "고소하고 퍽퍽한 노른자를 고구마 무스처럼 부드럽게", texture: "묽은 죽", ingredients: "계란 노른자 1개, 고구마 15g, 쌀 25g", recipe: ["1. 계란 완숙 삶기", "2. 고구마 쪄서 으깨고 노른자와 섞어 끓인 밥에 올리기"] },
    { id: "m32", name: "노른자 애호박 죽", age: "mid", goal: "all", allergens: ["egg"], desc: "위장이 편안한 소화 만점 아침 식사", texture: "묽은 죽", ingredients: "계란 노른자 1개, 애호박 15g, 쌀 25g", recipe: ["1. 애호박 다지기", "2. 죽 끓이다 마지막에 노른자 으깨 넣기"] },
    { id: "m33", name: "퀴노아 닭고기 당근 죽", age: "mid", goal: "weight", allergens: [], desc: "슈퍼푸드 퀴노아의 단백질이 듬뿍 들어간 닭죽", texture: "7배죽", ingredients: "닭안심 20g, 당근 10g, 불린 퀴노아 10g, 쌀 15g", recipe: ["1. 퀴노아 푹 불리기", "2. 닭/당근 다져 퀴노아와 끓이기"] },
    { id: "m34", name: "오트밀 소고기 시금치 죽", age: "mid", goal: "iron", allergens: [], desc: "변비 없는 철분 폭탄! 쌀 대신 오트밀로 만든 죽", texture: "부드러운 죽", ingredients: "소고기 20g, 시금치 10g, 퀵오트밀 25g", recipe: ["1. 소고기 다지기", "2. 시금치 데쳐 다지기", "3. 오트밀에 고기육수 부어 끓이기"] },
    { id: "m35", name: "두부 양배추 죽", age: "mid", goal: "poop", allergens: ["soy"], desc: "고기 식단 중간에 쉬어가는 속 편안한 식물성 죽", texture: "7배죽", ingredients: "두부 15g, 양배추 15g, 쌀 25g", recipe: ["1. 두부 데쳐 으깨기", "2. 양배추 다져 채수에 끓이기"] },

    // ---------------- [공장장 1차 추가분: 후기 이유식 15종] ----------------
    { id: "l21", name: "소고기 연근 진밥", age: "late", goal: "iron", allergens: [], desc: "아삭한 식감 훈련! 씹는 맛이 있는 철분 덮밥", texture: "4배 진밥", ingredients: "소고기 30g, 연근 15g, 진밥 50g", recipe: ["1. 연근 식초물 데쳐 아주 잘게 다지기", "2. 고기 볶다 진밥 넣고 졸이기"] },
    { id: "l22", name: "소고기 파프리카 진밥", age: "late", goal: "iron", allergens: [], desc: "파프리카의 단맛이 고기의 풍미를 한껏 끌어올림", texture: "진밥", ingredients: "소고기 30g, 파프리카 15g, 양파 10g, 진밥 50g", recipe: ["1. 파프리카 껍질 까고 다지기", "2. 고기 볶다 밥 넣고 끓이기"] },
    { id: "l23", name: "소고기 콩나물 진밥", age: "late", goal: "iron", allergens: [], desc: "콩나물 특유의 시원함이 살아있는 아기국밥 스타일", texture: "촉촉한 진밥", ingredients: "소고기 30g, 콩나물 15g, 진밥 50g", recipe: ["1. 콩나물 머리/꼬리 떼고 다지기", "2. 육수 붓고 고기와 졸이기"] },
    { id: "l24", name: "소고기 무 버섯 진밥", age: "late", goal: "iron", allergens: [], desc: "소고기 뭇국에 밥 말아먹는 듯한 든든함", texture: "국물 자박한 진밥", ingredients: "소고기 30g, 무 10g, 표고버섯 10g, 진밥 50g", recipe: ["1. 무와 버섯 다지기", "2. 고기와 볶다 물 붓고 밥 졸이기"] },
    { id: "l25", name: "닭고기 가지 진밥", age: "late", goal: "weight", allergens: [], desc: "가지를 푹 익혀 입에서 사르르 녹게 만든 닭고기 덮밥", texture: "부드러운 진밥", ingredients: "닭안심 30g, 가지 20g, 진밥 50g", recipe: ["1. 가지 껍질 벗겨 다지기", "2. 닭육수에 고기/가지/밥 끓이기"] },
    { id: "l26", name: "닭고기 감자 치즈 진밥", age: "late", goal: "weight", allergens: ["dairy"], desc: "고소함의 끝판왕! 감자와 치즈가 만나 풍미 대폭발", texture: "꾸덕한 리조또 느낌", ingredients: "닭안심 30g, 감자 20g, 아기치즈 1장, 진밥 50g", recipe: ["1. 감자 깍둑썰어 볶기", "2. 닭과 밥 끓이다 마지막에 치즈 녹이기"] },
    { id: "l27", name: "닭고기 브로콜리 치즈 리조또", age: "late", goal: "weight", allergens: ["dairy"], desc: "레스토랑 부럽지 않은 프리미엄 서양식 특식", texture: "크리미한 리조또", ingredients: "닭안심 30g, 브로콜리 15g, 아기치즈 1/2장, 진밥 50g", recipe: ["1. 브로콜리 다지기", "2. 닭/밥 끓이다 치즈 넣어 비비기"] },
    { id: "l28", name: "흰살생선 양파 진밥", age: "late", goal: "all", allergens: ["seafood"], desc: "양파가 생선 비린내를 완벽히 잡아주는 담백한 밥", texture: "진밥", ingredients: "대구살 30g, 양파 15g, 진밥 50g", recipe: ["1. 대구 가시 제거", "2. 양파 현미유 볶다 생선/밥 넣고 볶기"] },
    { id: "l29", name: "연어 아스파라거스 진밥", age: "late", goal: "weight", allergens: ["seafood"], desc: "고급 레스토랑의 연어 스테이크 느낌을 살린 밥", texture: "진밥", ingredients: "생물 연어 20g, 아스파라거스 10g, 진밥 50g", recipe: ["1. 아스파라거스 껍질 벗겨 봉우리만 다지기", "2. 연어 으깨어 밥과 끓이기"] },
    { id: "l30", name: "새우살 파프리카 진밥", age: "late", goal: "weight", allergens: ["shellfish"], desc: "알록달록 색감과 새우의 감칠맛이 폭발하는 볶음밥", texture: "볶음진밥", ingredients: "새우살 20g, 파프리카 15g, 양파 10g, 진밥 50g", recipe: ["1. 새우 내장 빼고 다지기", "2. 야채 볶다 새우/밥 넣고 촉촉하게 볶기"] },
    { id: "l31", name: "게살 계란 볶음밥", age: "late", goal: "weight", allergens: ["shellfish", "egg"], desc: "중화요리 게살 볶음밥의 무염 아기 버전", texture: "무른 볶음밥", ingredients: "크래미 20g, 계란 1개, 대파 약간, 진밥 50g", recipe: ["1. 대파 향 내어 기름에 볶기", "2. 스크램블 에그와 게살 찢어 밥과 볶기"] },
    { id: "l32", name: "소고기 배추 된장 진밥", age: "late", goal: "iron", allergens: ["soy"], desc: "아기 된장(무염/저염)으로 구수하게 끓여낸 한식 특식", texture: "국물 자박한 진밥", ingredients: "소고기 30g, 배추 15g, 아기된장 한 꼬집, 진밥 50g", recipe: ["1. 고기/배추 다지기", "2. 물 붓고 아기된장 살짝 풀어 밥과 졸이기"] },
    { id: "l33", name: "닭고기 고구마 사과 진밥", age: "late", goal: "poop", allergens: [], desc: "달콤함이 팡팡! 입맛 잃은 아기를 위한 최고의 치트키", texture: "촉촉한 진밥", ingredients: "닭안심 20g, 고구마 15g, 사과 15g, 진밥 50g", recipe: ["1. 고구마/사과 다지기", "2. 닭과 함께 푹 졸이기"] },
    { id: "l34", name: "치즈 고구마 진밥", age: "late", goal: "poop", allergens: ["dairy"], desc: "단짠단짠의 정석! 반찬 없을 때 뚝딱 비비는 마법의 밥", texture: "꾸덕한 진밥", ingredients: "고구마 30g, 아기치즈 1장, 진밥 50g", recipe: ["1. 고구마 푹 쪄서 으깨기", "2. 따뜻한 진밥에 고구마와 치즈 넣고 비비기"] },
    { id: "l35", name: "아보카도 계란 간장 비빔밥", age: "late", goal: "weight", allergens: ["egg", "soy"], desc: "간장계란밥의 프리미엄 영양 업그레이드 버전", texture: "비빔밥", ingredients: "아보카도 1/4개, 계란 1개, 아기간장 1t, 진밥 50g", recipe: ["1. 계란 프라이(노른자 완숙)", "2. 아보카도 으깨서 간장 1t 넣고 밥에 비비기"] },

    // ---------------- [공장장 1차 추가분: 완료기 유아식 10종] ----------------
    { id: "d16", name: "소고기 가지 볶음", age: "done", goal: "iron", allergens: ["soy"], desc: "어른 반찬 부럽지 않은 촉촉한 한식 반찬", texture: "촉촉한 볶음", ingredients: "다진 소고기 40g, 가지 30g, 양파 10g, 아기간장 1t", recipe: ["1. 가지 껍질 까고 깍둑썰기", "2. 고기 볶다 가지, 양파, 간장 넣고 부드럽게 볶기"] },
    { id: "d17", name: "닭고기 브로콜리 볶음", age: "done", goal: "weight", allergens: [], desc: "면역력을 지켜주는 담백한 순살 볶음", texture: "순살 볶음", ingredients: "닭다리살 40g, 브로콜리 20g, 현미유 1t", recipe: ["1. 닭다리살 껍질 벗겨 한입 크기", "2. 브로콜리 데쳐 팬에 닭과 노릇하게 굽기"] },
    { id: "d18", name: "대구살 무조림", age: "done", goal: "all", allergens: ["seafood", "soy"], desc: "달큰한 무와 부드러운 생선의 조합", texture: "부드러운 조림", ingredients: "대구살 40g, 무 30g, 아기간장 1t", recipe: ["1. 무 도톰하게 썰어 바닥에 깔기", "2. 대구살 올리고 물, 간장 부어 무가 뭉개질 때까지 졸이기"] },
    { id: "d19", name: "토마토 소고기 파스타", age: "done", goal: "iron", allergens: ["flour"], desc: "생토마토로 만든 새콤달콤 진짜 볼로네제 파스타", texture: "면 요리", ingredients: "소고기 30g, 토마토 1개, 양파 10g, 아기면 50g", recipe: ["1. 토마토 데쳐 껍질 벗기고 갈기", "2. 고기/양파 볶다 소스 부어 끓여 면 비비기"] },
    { id: "d20", name: "새우살 야채 볶음밥", age: "done", goal: "weight", allergens: ["shellfish"], desc: "중국집 볶음밥보다 맛있는 아기용 고슬고슬 볶음밥", texture: "볶음밥", ingredients: "새우살 30g, 다진 야채 20g, 현미유 1T, 밥 70g", recipe: ["1. 새우살 다져 야채와 볶기", "2. 밥 넣고 센 불에 수분 날리며 볶기"] },
    { id: "d21", name: "소고기 두부 덮밥", age: "done", goal: "iron", allergens: ["soy", "flour"], desc: "맵지 않은 아기용 마파두부 스타일 덮밥", texture: "덮밥 소스", ingredients: "소고기 30g, 깍둑썬 두부 30g, 아기간장 1t, 전분물 1T", recipe: ["1. 고기 볶다 물, 두부, 간장 넣고 끓이기", "2. 전분물 풀어 걸쭉하게 만들어 밥에 올리기"] },
    { id: "d22", name: "아보카도 바나나 머핀", age: "done", goal: "weight", allergens: ["flour", "egg"], desc: "건강한 지방과 과일 단맛으로 구워낸 노슈거 빵 간식", texture: "촉촉한 빵", ingredients: "아보카도 1/4개, 바나나 1/2개, 밀가루 30g, 계란 1개", recipe: ["1. 아보카도/바나나 으깨 계란, 밀가루 섞기", "2. 머핀 틀에 넣어 170도 오븐 15분 굽기"] },
    { id: "d23", name: "연어 스테이크", age: "done", goal: "weight", allergens: ["seafood", "dairy"], desc: "버터 향이 솔솔 나는 프리미엄 두뇌 발달 반찬", texture: "부드러운 생선구이", ingredients: "생물 연어 50g, 무염버터 1t", recipe: ["1. 연어 가시 확인 후 버터 두른 팬에 굽기", "2. 속까지 완전히 익혀 포크로 부숴주며 급여"] },
    { id: "d24", name: "단호박 에그슬럿", age: "done", goal: "weight", allergens: ["egg", "dairy"], desc: "미니 단호박 속에 치즈와 계란이 듬뿍 들어간 영양 폭탄", texture: "부드러운 찜", ingredients: "미니단호박 1개, 계란 1개, 아기치즈 1장", recipe: ["1. 단호박 전자렌지 2분 돌려 속 파내기", "2. 계란 깨 넣고 노른자 터뜨려 치즈 올리기", "3. 렌지 3분 더 돌려 익히기"] },
    { id: "d25", name: "감자 치즈 전", age: "done", goal: "all", allergens: ["dairy", "egg", "flour"], desc: "비 오는 날 해주는 쫀득쫀득 겉바속촉 핑거푸드", texture: "쫀득한 부침개", ingredients: "감자 1개, 아기치즈 1장, 부침가루 1T", recipe: ["1. 감자 강판에 갈아 물기 꼭 짜기", "2. 부침가루 섞어 반죽", "3. 팬에 굽다 가운데 치즈 올려 반 접어 굽기"] },

// ---------------- [공장장 2차 추가분: 초기 이유식 10종] ----------------
    { id: "e26", name: "소고기 적채 미음", age: "early", goal: "iron", allergens: [], desc: "시각 발달을 돕는 예쁜 보라색 고기 미음", texture: "10배 미음", ingredients: "소고기 10g, 적채(적양배추) 10g, 쌀가루 15g", recipe: ["1. 소고기 핏물 빼고 삶기", "2. 적채는 두꺼운 심지를 제거하고 잎만 찌기", "3. 믹서에 갈아 쌀가루와 끓이기"] },
    { id: "e27", name: "소고기 콜리플라워 미음", age: "early", goal: "iron", allergens: [], desc: "브로콜리보다 부드러워 초기 소화에 좋은 미음", texture: "10배 미음", ingredients: "소고기 10g, 콜리플라워 10g, 쌀가루 15g", recipe: ["1. 콜리플라워 꽃송이만 데치기", "2. 삶은 소고기와 함께 갈아 끓이기"] },
    { id: "e28", name: "닭고기 단호박 미음", age: "early", goal: "weight", allergens: [], desc: "담백한 닭안심에 단호박의 단맛을 입혀 거부감 제로", texture: "10배 미음", ingredients: "닭안심 10g, 단호박 10g, 쌀가루 15g", recipe: ["1. 닭안심 푹 삶기", "2. 단호박 껍질/씨 빼고 쪄서 함께 갈기", "3. 끓이기"] },
    { id: "e29", name: "오트밀 배 미음", age: "early", goal: "poop", allergens: [], desc: "감기 예방과 쾌변을 동시에 잡는 마법의 조합", texture: "주르륵 흐르는 미음", ingredients: "오트밀가루 10g, 배 10g, 쌀가루 10g", recipe: ["1. 배는 강판에 갈아즙을 내기", "2. 오트밀과 쌀가루 물에 풀어 끓이다 배즙 섞기"] },
    { id: "e30", name: "청경채 사과 미음", age: "early", goal: "poop", allergens: [], desc: "야채 거부감을 사과의 단맛으로 완벽하게 숨긴 미음", texture: "10배 미음", ingredients: "청경채 10g, 사과 10g, 쌀가루 15g", recipe: ["1. 청경채 잎만 데치기", "2. 사과 갈아서 쌀가루, 청경채와 함께 끓이기"] },
    { id: "e31", name: "브로콜리 감자 미음", age: "early", goal: "all", allergens: [], desc: "비타민과 탄수화물이 만나 든든하고 면역력에 좋은 미음", texture: "10배 미음", ingredients: "브로콜리 꽃송이 10g, 감자 10g, 쌀가루 15g", recipe: ["1. 브로콜리 데치고 감자 찌기", "2. 함께 믹서에 갈아 끓이기"] },
    { id: "e32", name: "적채 사과 퓨레", age: "early", goal: "poop", allergens: [], desc: "색감 천재! 눈으로 한 번, 입으로 두 번 먹는 간식", texture: "부드러운 퓨레", ingredients: "적채 10g, 사과 1/4쪽", recipe: ["1. 적채 잎 푹 찌기", "2. 사과 갈아서 적채와 함께 믹서에 곱게 으깨기"] },
    { id: "e33", name: "완두콩 사과 퓨레", age: "early", goal: "weight", allergens: [], desc: "식물성 단백질이 풍부한 초기 살찌우기 퓨레", texture: "퓨레", ingredients: "완두콩 10g, 사과 1/4쪽", recipe: ["1. 완두콩 푹 삶아 투명한 껍질 완벽히 까기", "2. 사과 갈아 섞어 부드럽게 으깨기"] },
    { id: "e34", name: "오이 사과 미음", age: "early", goal: "all", allergens: [], desc: "청량감 100%! 여름철 땀 많이 흘린 아기 수분 보충", texture: "묽은 미음", ingredients: "오이 10g, 사과 10g, 쌀가루 15g", recipe: ["1. 오이 껍질/씨 제거하고 강판에 갈기", "2. 사과즙과 함께 쌀가루 풀어 끓이기"] },
    { id: "e35", name: "수박 퓨레", age: "early", goal: "all", allergens: [], desc: "열날 때 먹이기 좋은 천연 해열제 간식", texture: "수분감 폭발 퓨레", ingredients: "수박 과육 30g", recipe: ["1. 수박 씨를 완벽하게 빼고 과육만 바르기", "2. 믹서에 아주 살짝만 갈아 액상 형태로 급여"] },

    // ---------------- [공장장 2차 추가분: 중기 이유식 15종] ----------------
    { id: "m36", name: "소고기 미역 단호박 죽", age: "mid", goal: "poop", allergens: [], desc: "배변 황금 조합(미역+단호박)에 철분을 입힌 완벽죽", texture: "7배죽", ingredients: "소고기 20g, 불린 미역 10g, 단호박 15g, 쌀 25g", recipe: ["1. 미역 짠기 빼고 아주 잘게 다지기", "2. 단호박 찌기", "3. 고기와 함께 푹 끓이기"] },
    { id: "m37", name: "소고기 아욱 죽", age: "mid", goal: "iron", allergens: [], desc: "성장기 뼈 발달에 좋은 아욱을 푹 끓여낸 보양죽", texture: "7배죽", ingredients: "소고기 20g, 아욱 15g, 쌀 25g", recipe: ["1. 아욱의 질긴 줄기 떼고 바락바락 주물러 푸른 물 빼기", "2. 고기와 다져 끓이기"] },
    { id: "m38", name: "소고기 오이 배 죽", age: "mid", goal: "all", allergens: [], desc: "기관지염이나 감기 걸렸을 때 넘기기 좋은 시원한 죽", texture: "묽은 7배죽", ingredients: "소고기 20g, 오이 10g, 배 15g, 쌀 25g", recipe: ["1. 오이 껍질/씨 빼고 다지기", "2. 배 갈아서 고기, 쌀과 함께 끓이기"] },
    { id: "m39", name: "닭고기 적채 죽", age: "mid", goal: "weight", allergens: [], desc: "적채의 예쁜 색감이 닭죽을 한층 고급스럽게 만듦", texture: "7배죽", ingredients: "닭안심 20g, 적채 15g, 쌀 25g", recipe: ["1. 적채 잎만 푹 쪄서 다지기", "2. 닭고기 삶아 다진 후 육수에 끓이기"] },
    { id: "m40", name: "닭고기 양배추 사과 죽", age: "mid", goal: "poop", allergens: [], desc: "소화력 증진의 끝판왕. 장염 후 회복식으로 강력 추천", texture: "부드러운 죽", ingredients: "닭안심 20g, 양배추 15g, 사과 10g, 쌀 25g", recipe: ["1. 양배추 다지기", "2. 닭육수에 끓이다 마지막에 다진 사과 넣기"] },
    { id: "m41", name: "대구살 브로콜리 당근 죽", age: "mid", goal: "all", allergens: ["seafood"], desc: "색감 밸런스가 좋은 흰살생선 국민 레시피", texture: "7배죽", ingredients: "대구살 20g, 브로콜리 10g, 당근 10g, 쌀 25g", recipe: ["1. 대구살 가시 제거 후 으깨기", "2. 당근/브로콜리 다져 채수에 끓이기"] },
    { id: "m42", name: "가자미 연근 죽", age: "mid", goal: "poop", allergens: ["seafood"], desc: "설사 잡는 연근과 담백한 가자미의 찰떡 궁합", texture: "7배죽", ingredients: "가자미 20g, 연근 10g, 쌀 25g", recipe: ["1. 연근 식초물 데쳐 아주 잘게 다지기", "2. 가자미살과 함께 끓이기"] },
    { id: "m43", name: "노른자 콜리플라워 죽", age: "mid", goal: "iron", allergens: ["egg"], desc: "노른자의 퍽퍽함을 콜리플라워의 부드러움으로 잡은 죽", texture: "묽은 죽", ingredients: "계란 노른자 1개, 콜리플라워 15g, 쌀 25g", recipe: ["1. 콜리플라워 꽃송이 다져 쌀과 끓이기", "2. 노른자 완숙 으깨서 섞기"] },
    { id: "m44", name: "검은콩 단호박 죽", age: "mid", goal: "weight", allergens: ["soy"], desc: "식물성 단백질과 탄수화물이 만나 든든하게 살찌우기", texture: "크리미한 죽", ingredients: "검은콩 10g, 단호박 15g, 쌀 25g", recipe: ["1. 검은콩 불려 껍질 까고 삶아 으깨기", "2. 단호박 으깨 함께 끓이기"] },
    { id: "m45", name: "오트밀 닭고기 당근 죽", age: "mid", goal: "weight", allergens: [], desc: "철분 흡수율을 극대화한 오트밀 닭죽", texture: "부드러운 죽", ingredients: "퀵오트밀 20g, 닭안심 20g, 당근 10g", recipe: ["1. 닭/당근 다져 육수에 끓이기", "2. 오트밀 넣고 3분 더 끓여 퍼지게 하기"] },
    { id: "m46", name: "렌틸콩 소고기 브로콜리 죽", age: "mid", goal: "iron", allergens: [], desc: "슈퍼푸드 렌틸콩이 들어간 철분 더블 폭탄 죽", texture: "7배죽", ingredients: "레드렌틸콩 10g, 소고기 20g, 브로콜리 10g, 쌀 15g", recipe: ["1. 렌틸콩 푹 삶기", "2. 고기/브로콜리 다져 쌀, 렌틸콩과 끓이기"] },
    { id: "m47", name: "두부 버섯 죽", age: "mid", goal: "all", allergens: ["soy"], desc: "감칠맛과 고소함이 만나 고기 없이도 잘 먹는 식물성 죽", texture: "7배죽", ingredients: "두부 15g, 양송이버섯(또는 표고) 10g, 쌀 25g", recipe: ["1. 두부 데쳐 으깨기", "2. 버섯 다져 채수에 푹 끓이기"] },
    { id: "m48", name: "소고기 청경채 팽이버섯 죽", age: "mid", goal: "iron", allergens: [], desc: "팽이버섯의 쫄깃한 식감에 적응하는 중기 죽", texture: "7배죽", ingredients: "소고기 20g, 청경채 10g, 팽이버섯 10g, 쌀 25g", recipe: ["1. 팽이버섯 아주 잘게 다지기 (안 그러면 똥으로 나옴)", "2. 다 같이 끓이기"] },
    { id: "m49", name: "닭고기 수수 고구마 죽", age: "mid", goal: "weight", allergens: [], desc: "항산화 성분이 풍부한 수수를 활용한 달콤한 건강죽", texture: "7배죽", ingredients: "닭안심 20g, 찰수수 5g, 고구마 10g, 쌀 20g", recipe: ["1. 찰수수는 하루 전 불리고 푹 삶아 떫은맛 빼기", "2. 고구마 으깨 닭고기와 끓이기"] },
    { id: "m50", name: "연어 감자 당근 죽", age: "mid", goal: "weight", allergens: ["seafood"], desc: "연어의 고소한 풍미와 감자의 든든함. 두뇌발달 특식", texture: "7배죽", ingredients: "생물 연어 20g, 감자 10g, 당근 10g, 쌀 25g", recipe: ["1. 연어 쪄서 으깨기", "2. 감자/당근 다져 끓이다 연어 섞기"] },

    // ---------------- [공장장 2차 추가분: 후기 이유식 15종] ----------------
    { id: "l36", name: "소고기 아스파라거스 진밥", age: "late", goal: "iron", allergens: [], desc: "아스파라긴산으로 피로 회복! 고급 레스토랑 느낌 진밥", texture: "진밥", ingredients: "소고기 30g, 아스파라거스 15g, 양파 10g, 진밥 50g", recipe: ["1. 아스파라거스 껍질 벗겨 봉우리만 다지기", "2. 고기 볶다 진밥 넣고 끓이기"] },
    { id: "l37", name: "소고기 비트 치즈 리조또", age: "late", goal: "iron", allergens: ["dairy"], desc: "강렬한 핑크빛 소고기 치즈밥! 시각 자극 끝판왕", texture: "꾸덕한 리조또", ingredients: "소고기 30g, 비트 15g, 아기치즈 1장, 진밥 50g", recipe: ["1. 비트 쪄서 다지기", "2. 고기 볶다 밥/물 끓이고 마지막 치즈 녹이기"] },
    { id: "l38", name: "소고기 팽이버섯 덮밥", age: "late", goal: "weight", allergens: [], desc: "버섯 불고기 느낌의 달짝지근한 소고기 덮밥", texture: "촉촉한 진밥", ingredients: "소고기 30g, 팽이버섯 15g, 양파 10g, 진밥 50g", recipe: ["1. 팽이버섯 잘게 다져 양파와 볶기", "2. 육수 부어 자박하게 졸이기"] },
    { id: "l39", name: "닭고기 렌틸콩 진밥", age: "late", goal: "weight", allergens: [], desc: "고단백 렌틸콩을 넣어 성장기 아기 근육 발달에 최고", texture: "진밥", ingredients: "닭안심 30g, 레드렌틸콩 15g, 당근 10g, 진밥 50g", recipe: ["1. 렌틸콩 푹 삶기", "2. 닭고기 다져 렌틸콩/밥과 졸이기"] },
    { id: "l40", name: "닭고기 시금치 당근 진밥", age: "late", goal: "all", allergens: [], desc: "가장 클래식하고 영양 밸런스가 완벽한 삼색 진밥", texture: "진밥", ingredients: "닭안심 30g, 시금치 15g, 당근 10g, 진밥 50g", recipe: ["1. 시금치 데쳐 물 버리고 다지기", "2. 당근/고기 볶다 밥과 졸이기"] },
    { id: "l41", name: "대구살 콩나물 무 진밥", age: "late", goal: "all", allergens: ["seafood"], desc: "아기용 대구 맑은탕 뚝배기에 밥 말아먹는 시원한 맛", texture: "국물 자박한 진밥", ingredients: "대구살 30g, 콩나물 10g, 무 10g, 진밥 50g", recipe: ["1. 콩나물 꼬리/머리 떼고 다지기", "2. 무/대구살 끓이다 밥 말기"] },
    { id: "l42", name: "연어 브로콜리 양파 진밥", age: "late", goal: "weight", allergens: ["seafood"], desc: "양파로 비린내를 잡은 고소한 연어 덮밥", texture: "진밥", ingredients: "연어 30g, 브로콜리 10g, 양파 10g, 진밥 50g", recipe: ["1. 양파 현미유에 볶아 단맛 내기", "2. 찐 연어 으깨어 브로콜리/밥과 섞기"] },
    { id: "l43", name: "새우살 계란 볶음밥", age: "late", goal: "weight", allergens: ["shellfish", "egg"], desc: "중화요리 부럽지 않은 탱글고소 계란 볶음밥", texture: "무른 볶음밥", ingredients: "새우살 20g, 계란 1개, 양파 10g, 진밥 50g", recipe: ["1. 새우살 다져 양파와 볶기", "2. 계란 스크램블어 밥과 촉촉하게 볶기"] },
    { id: "l44", name: "전복 표고버섯 진밥", age: "late", goal: "weight", allergens: ["seafood"], desc: "돌아기 보양식 1티어! 전복내장죽 부럽지 않은 특식", texture: "진밥", ingredients: "전복살 20g, 표고버섯 15g, 진밥 50g", recipe: ["1. 전복 내장 버리고 살만 푹 쪄서 다지기", "2. 표고버섯 다져 채수에 밥과 졸이기"] },
    { id: "l45", name: "치즈 감자 당근 진밥", age: "late", goal: "weight", allergens: ["dairy"], desc: "고기 똑 떨어졌을 때 구세주! 짭짤 고소한 치즈밥", texture: "꾸덕한 진밥", ingredients: "감자 20g, 당근 10g, 아기치즈 1장, 진밥 50g", recipe: ["1. 감자/당근 볶아 익히기", "2. 물 붓고 밥 끓이다 마지막 치즈 녹이기"] },
    { id: "l46", name: "노른자 애호박 양파 진밥", age: "late", goal: "all", allergens: ["egg"], desc: "위장이 편안하고 소화 잘되는 달큰한 노른자 비빔밥", texture: "비빔밥 스타일", ingredients: "계란 노른자 1개, 애호박 15g, 양파 10g, 진밥 50g", recipe: ["1. 애호박/양파 물로 볶아 익히기", "2. 노른자 완숙 으깨어 밥에 비비기"] },
    { id: "l47", name: "돼지고기 청경채 볶음밥", age: "late", goal: "weight", allergens: [], desc: "아기용 동파육 덮밥 느낌! 돼지고기 안심의 고소함", texture: "촉촉한 볶음진밥", ingredients: "돼지안심 30g, 청경채 15g, 양파 10g, 진밥 50g", recipe: ["1. 돼지고기 아주 잘게 다져 양파와 볶기", "2. 청경채 넣고 밥과 볶기"] },
    { id: "l48", name: "소고기 미역 깨 진밥", age: "late", goal: "poop", allergens: [], desc: "깨가루를 듬뿍 넣어 미역국에 밥 만 것보다 고소함", texture: "진밥", ingredients: "소고기 30g, 불린 미역 15g, 빻은 깨 1t, 진밥 50g", recipe: ["1. 미역 아주 잘게 다지기", "2. 고기 볶아 밥/물 졸이다 깨 섞기"] },
    { id: "l49", name: "두부 소고기 소보로 덮밥", age: "late", goal: "iron", allergens: ["soy"], desc: "물기 꽉 짠 두부와 고기를 소보로처럼 보슬보슬 볶은 밥", texture: "보슬보슬한 덮밥", ingredients: "소고기 20g, 물기 짠 두부 20g, 진밥 50g", recipe: ["1. 두부 물기 짜고 고기와 현미유에 바싹 볶기", "2. 진밥 위에 뿌려주기"] },
    { id: "l50", name: "닭고기 양배추 치즈 진밥", age: "late", goal: "poop", allergens: ["dairy"], desc: "치즈 닭갈비의 순한맛 아기 버전! 달콤하고 고소함", texture: "꾸덕한 진밥", ingredients: "닭안심 30g, 양배추 15g, 아기치즈 1장, 진밥 50g", recipe: ["1. 닭/양배추 다져 볶기", "2. 밥 넣고 물 자박하게 끓이다 치즈 녹이기"] },

    // ---------------- [공장장 2차 추가분: 완료기 유아식 10종] ----------------
    { id: "d26", name: "소고기 야채 볶음우동", age: "done", goal: "weight", allergens: ["flour", "soy"], desc: "밥 거부 올 때 직빵! 후루룩 넘어가는 아기용 볶음우동", texture: "쫄깃한 면 요리", ingredients: "소고기 30g, 양배추/당근 20g, 아기용 우동면 50g, 아기간장 1t", recipe: ["1. 우동면 삶아 잘게 자르기", "2. 고기/야채 현미유에 볶다 간장 1t 넣기", "3. 면 넣고 빠르게 볶기"] },
    { id: "d27", name: "베이컨(아기용) 크림 파스타", age: "done", goal: "weight", allergens: ["dairy", "flour"], desc: "생우유 섭취가 가능한 돌 이후 만들어주는 우유 크림 파스타", texture: "크리미한 면 요리", ingredients: "무첨가 아기베이컨(또는 닭고기) 20g, 양파 10g, 생우유 50ml, 아기치즈 1장, 아기면", recipe: ["1. 베이컨/양파 볶기", "2. 우유 붓고 치즈 녹여 소스 만들기", "3. 삶은 면 비비기"] },
    { id: "d28", name: "연어 두부 스테이크", age: "done", goal: "weight", allergens: ["seafood", "soy", "egg", "flour"], desc: "연어의 오메가3와 두부의 단백질로 만든 겉바속촉 패티", texture: "부드러운 패티", ingredients: "생연어 40g, 물기 짠 두부 30g, 전분 1T, 계란 1/2개", recipe: ["1. 연어 으깨고 두부/계란/전분 치대기", "2. 동그랗게 빚어 팬에 노릇하게 굽기"] },
    { id: "d29", name: "새우 야채 밥전", age: "done", goal: "all", allergens: ["shellfish", "egg", "flour"], desc: "냉장고 파먹기 최고! 밥태기 극복하는 마법의 밥전", texture: "고소한 부침개", ingredients: "다진 새우 20g, 다진 야채, 밥 40g, 계란 1개", recipe: ["1. 볼에 밥, 새우, 야채, 계란 섞기", "2. 현미유 두른 팬에 한 입 크기로 부치기"] },
    { id: "d30", name: "닭가슴살 큐브 사과 조림", age: "done", goal: "weight", allergens: ["soy"], desc: "사과의 단맛으로 닭가슴살의 퍽퍽함을 잡은 무염 반찬", texture: "부드러운 고기 조림", ingredients: "닭가슴살 40g, 사과 20g, 아기간장 1t", recipe: ["1. 닭 깍둑썰기", "2. 사과 강판에 갈아 간장과 섞기", "3. 팬에 닭 굽다 소스 부어 졸이기"] },
    { id: "d31", name: "전복 미역국 (유아식)", age: "done", goal: "iron", allergens: ["seafood", "soy"], desc: "돌아기 생일상에 올리는 깊고 진한 보양 국물", texture: "따뜻한 국물", ingredients: "전복 1마리, 불린 미역 20g, 아기간장 1t, 참기름 약간", recipe: ["1. 전복 내장 빼고 살만 얇게 슬라이스", "2. 참기름에 미역/전복 달달 볶기", "3. 물 붓고 푹 끓여 간장 톡"] },
    { id: "d32", name: "돼지고기 안심 탕수육 (오븐)", age: "done", goal: "weight", allergens: ["flour"], desc: "튀기지 않고 오븐에 구워 기름기 쏙 뺀 건강 탕수육", texture: "겉바속촉 고기튀김", ingredients: "돼지안심 50g, 전분가루, 사과/오이 약간(소스용)", recipe: ["1. 돼지고기 전분 묻혀 오븐/에프 180도 15분 굽기", "2. 과일 끓여 전분물로 걸쭉한 소스 만들기"] },
    { id: "d33", name: "오트밀 바나나 쿠키", age: "done", goal: "poop", allergens: ["egg"], desc: "밀가루, 설탕 0%! 바나나의 단맛으로만 구운 건강 쿠키", texture: "쫀득한 쿠키", ingredients: "푹 익은 바나나 1개, 퀵오트밀 50g, 계란 1개", recipe: ["1. 바나나 포크로 으깨고 오트밀/계란 섞기", "2. 에프/오븐 170도 15분 구워 식히기"] },
    { id: "d34", name: "계란말이 밥 (핑거푸드)", age: "done", goal: "weight", allergens: ["egg"], desc: "소풍 갈 때 최고! 밥을 품은 뚱뚱한 계란말이", texture: "폭신폭신한 계란밥", ingredients: "밥 40g, 다진 야채 10g, 계란 2개", recipe: ["1. 야채 볶아 밥과 섞어 길쭉하게 뭉치기", "2. 팬에 계란물 풀어 밥을 얹고 돌돌 말기"] },
    { id: "d35", name: "감자 치즈 볼", age: "done", goal: "weight", allergens: ["dairy", "egg", "flour"], desc: "한입 베어 물면 치즈가 쭈욱 늘어나는 간식", texture: "동그란 감자볼", ingredients: "감자 1개, 아기치즈 1장, 계란물, 빵가루", recipe: ["1. 감자 쪄서 으깨 동그랗게 빚기 (가운데 치즈 넣기)", "2. 계란물->빵가루 묻혀 에프 10분 굽기"] },

// ---------------- [공장장 3차 추가분: 초기 이유식 10종] ----------------
    { id: "e36", name: "소고기 완두콩 미음", age: "early", goal: "iron", allergens: [], desc: "고소한 완두콩이 들어가 풋내를 잡고 단백질을 높인 미음", texture: "10배 미음", ingredients: "소고기 10g, 완두콩 10g, 쌀가루 15g", recipe: ["1. 완두콩은 푹 삶아 투명한 껍질을 완벽히 벗기기", "2. 소고기 삶아 완두콩과 갈기", "3. 쌀가루와 끓이기"] },
    { id: "e37", name: "소고기 적채 사과 미음", age: "early", goal: "poop", allergens: [], desc: "적채의 보라색과 사과의 달콤함! 눈과 입이 즐거운 미음", texture: "10배 미음", ingredients: "소고기 10g, 적채 5g, 사과 5g, 쌀가루 15g", recipe: ["1. 적채는 잎만 찌고, 사과는 갈기", "2. 소고기와 함께 갈아서 끓이기"] },
    { id: "e38", name: "닭고기 콜리플라워 미음", age: "early", goal: "weight", allergens: [], desc: "하얗고 부드러워 초기 아기들이 가장 편안하게 넘기는 미음", texture: "10배 미음", ingredients: "닭안심 10g, 콜리플라워 10g, 쌀가루 15g", recipe: ["1. 콜리플라워 꽃송이만 데치기", "2. 닭안심 삶아 함께 갈고 끓이기"] },
    { id: "e39", name: "닭고기 비트 미음", age: "early", goal: "weight", allergens: [], desc: "비트의 철분과 닭고기의 단백질이 만난 영양 핑크죽", texture: "10배 미음", ingredients: "닭안심 10g, 비트 5g, 쌀가루 15g", recipe: ["1. 비트 껍질 벗겨 푹 찌기", "2. 닭안심과 갈아서 끓이기"] },
    { id: "e40", name: "단호박 고구마 퓨레", age: "early", goal: "weight", allergens: [], desc: "구황작물 끝판왕! 살찌우기 프로젝트 1등 공신 간식", texture: "부드러운 퓨레", ingredients: "단호박 15g, 고구마 15g", recipe: ["1. 단호박과 고구마 푹 찌기", "2. 따뜻할 때 분유/모유 한 스푼 넣고 으깨기"] },
    { id: "e41", name: "오트밀 사과 배 퓨레", age: "early", goal: "poop", allergens: [], desc: "변비가 올 틈을 주지 않는 상큼한 아침 식사 대용", texture: "주르륵 퓨레", ingredients: "퀵오트밀 10g, 사과 10g, 배 10g", recipe: ["1. 사과, 배 강판에 갈기", "2. 오트밀에 과일즙 섞어 전자렌지 30초 돌려 불리기"] },
    { id: "e42", name: "감자 사과 미음", age: "early", goal: "all", allergens: [], desc: "감자의 텁텁함을 사과의 상큼함으로 완벽하게 커버", texture: "10배 미음", ingredients: "감자 10g, 사과 10g, 쌀가루 15g", recipe: ["1. 감자 쪄서 으깨기", "2. 사과즙과 함께 쌀미음에 끓이기"] },
    { id: "e43", name: "아보카도 바나나 퓨레", age: "early", goal: "weight", allergens: [], desc: "불 없이 만드는 초간단 고열량 슈퍼푸드 간식", texture: "크리미한 퓨레", ingredients: "아보카도 10g, 바나나 10g", recipe: ["1. 껍질 까만 아보카도 과육 파내기", "2. 푹 익은 바나나와 포크로 부드럽게 으깨기"] },
    { id: "e44", name: "콜리플라워 사과 미음", age: "early", goal: "poop", allergens: [], desc: "야채 안 먹는 아기를 달래주는 마법의 단맛", texture: "10배 미음", ingredients: "콜리플라워 10g, 사과 10g, 쌀가루 15g", recipe: ["1. 콜리플라워 데쳐 사과와 함께 갈기", "2. 끓이기"] },
    { id: "e45", name: "적채 배 미음", age: "early", goal: "all", allergens: [], desc: "열날 때, 감기 기운 있을 때 목 넘김이 좋은 쿨링 미음", texture: "10배 미음", ingredients: "적채 10g, 배 10g, 쌀가루 15g", recipe: ["1. 적채 잎 데치고 배 갈기", "2. 갈아서 끓이기"] },

    // ---------------- [공장장 3차 추가분: 중기 이유식 15종] ----------------
    { id: "m51", name: "소고기 근대 죽", age: "mid", goal: "iron", allergens: [], desc: "시금치를 대체할 수 있는 훌륭한 철분 공급원 근대죽", texture: "7배죽", ingredients: "소고기 20g, 근대 15g, 쌀 25g", recipe: ["1. 근대 질긴 줄기 버리고 끓는 물에 데쳐 물 짜내고 다지기", "2. 소고기 육수에 푹 끓이기"] },
    { id: "m52", name: "소고기 비트 고구마 죽", age: "mid", goal: "poop", allergens: [], desc: "변비 예방과 철분 보충을 동시에! 달콤한 핑크 죽", texture: "7배죽", ingredients: "소고기 20g, 비트 5g, 고구마 15g, 쌀 25g", recipe: ["1. 비트/고구마 찌기", "2. 소고기 다져 함께 끓이기"] },
    { id: "m53", name: "닭고기 청경채 사과 죽", age: "mid", goal: "weight", allergens: [], desc: "아침 식사로 부담 없이 훌루룩 넘기기 좋은 닭죽", texture: "7배죽", ingredients: "닭안심 20g, 청경채 10g, 사과 10g, 쌀 25g", recipe: ["1. 청경채 데쳐 다지기", "2. 닭/청경채 끓이다 다진 사과 넣기"] },
    { id: "m54", name: "닭고기 퀴노아 배추 죽", age: "mid", goal: "weight", allergens: [], desc: "배추의 시원함에 퀴노아 단백질을 꽉 채운 보양죽", texture: "7배죽", ingredients: "닭안심 20g, 불린 퀴노아 10g, 배추 10g, 쌀 15g", recipe: ["1. 퀴노아 하루 전 푹 불리기", "2. 배추잎 다져 닭고기, 퀴노아와 끓이기"] },
    { id: "m55", name: "가자미 당근 양파 죽", age: "mid", goal: "all", allergens: ["seafood"], desc: "고소한 가자미살과 양파의 단맛이 만나 감칠맛 폭발", texture: "7배죽", ingredients: "가자미 20g, 당근 10g, 양파 10g, 쌀 25g", recipe: ["1. 가자미 쪄서 가시 확인", "2. 야채 다져 끓이기"] },
    { id: "m56", name: "대구살 렌틸콩 브로콜리 죽", age: "mid", goal: "iron", allergens: ["seafood"], desc: "생선 베이스에 철분이 부족할까 걱정된다면 렌틸콩 추가!", texture: "7배죽", ingredients: "대구살 20g, 레드렌틸콩 10g, 브로콜리 10g, 쌀 15g", recipe: ["1. 렌틸콩 삶기", "2. 대구살 가시 제거", "3. 브로콜리 다져 다 같이 끓이기"] },
    { id: "m57", name: "노른자 단호박 무 죽", age: "mid", goal: "all", allergens: ["egg"], desc: "무가 들어가 소화도 잘되고 단호박으로 달콤한 노란죽", texture: "묽은 7배죽", ingredients: "계란 노른자 1개, 단호박 15g, 무 10g, 쌀 25g", recipe: ["1. 단호박/무 쪄서 으깨거나 다지기", "2. 쌀과 끓이다 노른자 으깨 넣기"] },
    { id: "m58", name: "소고기 양송이 당근 죽", age: "mid", goal: "iron", allergens: [], desc: "양송이의 부드러움이 소고기와 찰떡 궁합인 기본죽", texture: "7배죽", ingredients: "소고기 20g, 양송이버섯 15g, 당근 10g, 쌀 25g", recipe: ["1. 양송이 껍질 살짝 벗겨 다지기", "2. 소고기/당근 다져 끓이기"] },
    { id: "m59", name: "닭고기 아보카도 고구마 죽", age: "mid", goal: "weight", allergens: [], desc: "이유식 정체기 극복! 가장 부드럽고 달콤고소한 죽", texture: "크리미한 죽", ingredients: "닭안심 20g, 아보카도 10g, 고구마 15g, 쌀 25g", recipe: ["1. 고구마 찌고 아보카도 으깨기", "2. 닭죽 끓이다 과육 섞기"] },
    { id: "m60", name: "검은콩 소고기 배추 죽", age: "mid", goal: "iron", allergens: ["soy"], desc: "식물성 단백질과 동물성 철분의 완벽한 조화", texture: "7배죽", ingredients: "검은콩 10g, 소고기 20g, 배추 10g, 쌀 25g", recipe: ["1. 콩 불려 껍질 까고 삶아 으깨기", "2. 배추 다져 소고기와 끓이기"] },
    { id: "m61", name: "두부 청경채 당근 죽", age: "mid", goal: "all", allergens: ["soy"], desc: "고기 식단 사이 위장을 가볍게 비워주는 식물성 죽", texture: "7배죽", ingredients: "두부 15g, 청경채 10g, 당근 10g, 쌀 25g", recipe: ["1. 두부 데쳐 으깨기", "2. 청경채/당근 다져 채수에 끓이기"] },
    { id: "m62", name: "병아리콩 닭고기 당근 죽", age: "mid", goal: "weight", allergens: ["soy"], desc: "밤처럼 고소한 병아리콩으로 살찌우는 영양 만점 닭죽", texture: "7배죽", ingredients: "병아리콩 10g, 닭안심 20g, 당근 10g, 쌀 20g", recipe: ["1. 병아리콩 불려 껍질 까고 푹 삶아 으깨기", "2. 닭고기와 끓이기"] },
    { id: "m63", name: "연어 감자 시금치 죽", age: "mid", goal: "weight", allergens: ["seafood"], desc: "오메가3 폭발! 연어의 풍미를 감자가 부드럽게 감싸줌", texture: "7배죽", ingredients: "생물 연어 20g, 감자 15g, 시금치 10g, 쌀 25g", recipe: ["1. 연어 쪄서 으깨기", "2. 감자/시금치 다져 끓이기"] },
    { id: "m64", name: "대구살 비타민 죽", age: "mid", goal: "all", allergens: ["seafood"], desc: "흰살생선 베이스에 철분을 보완해주는 심플한 레시피", texture: "7배죽", ingredients: "대구살 20g, 비타민(다채) 15g, 쌀 25g", recipe: ["1. 대구 쪄서 가시 제거", "2. 비타민 잎 데쳐 다지고 생선살과 끓이기"] },
    { id: "m65", name: "소고기 미역 오트밀 죽", age: "mid", goal: "poop", allergens: [], desc: "미역과 오트밀이 만나 쾌변 고속도로를 뚫어주는 죽", texture: "부드러운 7배죽", ingredients: "소고기 20g, 불린 미역 10g, 퀵오트밀 25g", recipe: ["1. 미역 짠기 완벽히 빼고 아주 잘게 다지기", "2. 소고기와 끓이다 오트밀 넣어 퍼지게 하기"] },

    // ---------------- [공장장 3차 추가분: 후기 이유식 15종] ----------------
    { id: "l51", name: "소고기 우엉 진밥", age: "late", goal: "iron", allergens: [], desc: "김밥 속 우엉처럼 향긋! 뿌리채소의 영양을 듬뿍", texture: "진밥", ingredients: "소고기 30g, 우엉 10g, 당근 10g, 진밥 50g", recipe: ["1. 우엉 껍질 벗겨 식초물 데치고 아주 잘게 다지기", "2. 고기 볶다 진밥 넣고 끓이기"] },
    { id: "l52", name: "소고기 아보카도 토마토 리조또", age: "late", goal: "weight", allergens: [], desc: "치즈 없이 아보카도로 크리미함을 살린 건강 리조또", texture: "꾸덕한 리조또", ingredients: "소고기 30g, 후숙 아보카도 15g, 방울토마토 2개, 진밥 50g", recipe: ["1. 토마토 데쳐 껍질 까고 다지기", "2. 고기/토마토/밥 끓이다 아보카도 으깨 섞기"] },
    { id: "l53", name: "닭고기 파프리카 고구마 진밥", age: "late", goal: "weight", allergens: [], desc: "파프리카의 향긋함과 고구마의 달콤함이 어우러진 특식", texture: "진밥", ingredients: "닭안심 30g, 파프리카 15g, 고구마 15g, 진밥 50g", recipe: ["1. 파프리카 껍질 까고 다지기", "2. 닭/고구마/파프리카 볶아 밥과 끓이기"] },
    { id: "l54", name: "닭고기 시금치 치즈 진밥", age: "late", goal: "iron", allergens: ["dairy"], desc: "시금치 안 먹는 아이들을 치즈로 현혹하는 마법", texture: "꾸덕한 진밥", ingredients: "닭안심 30g, 시금치 15g, 아기치즈 1장, 진밥 50g", recipe: ["1. 시금치 데쳐 다지기", "2. 닭/밥 끓이다 치즈 녹이기"] },
    { id: "l55", name: "새우살 가지 볶음 진밥", age: "late", goal: "weight", allergens: ["shellfish"], desc: "중화요리 칠리새우가지 느낌의 순한맛 아기 버전", texture: "볶음 진밥", ingredients: "새우살 20g, 가지 15g, 양파 10g, 진밥 50g", recipe: ["1. 가지/새우 다져 양파와 현미유에 볶기", "2. 진밥 넣고 촉촉하게 볶기"] },
    { id: "l56", name: "새우살 단호박 리조또", age: "late", goal: "weight", allergens: ["shellfish", "dairy"], desc: "레스토랑 뺨치는 노란빛의 프리미엄 해산물 밥", texture: "리조또", ingredients: "새우살 20g, 단호박 15g, 아기치즈 1/2장, 진밥 50g", recipe: ["1. 단호박 쪄서 으깨기", "2. 새우 볶다 단호박/밥 넣고 치즈 녹이기"] },
    { id: "l57", name: "흰살생선 연근 당근 진밥", age: "late", goal: "all", allergens: ["seafood"], desc: "아삭한 식감 훈련에 좋은 담백하고 고소한 생선밥", texture: "진밥", ingredients: "대구살 30g, 연근 10g, 당근 10g, 진밥 50g", recipe: ["1. 연근 식초물 데쳐 다지기", "2. 대구살 쪄서 가시 빼고 야채/밥과 졸이기"] },
    { id: "l58", name: "연어 양배추 양파 진밥", age: "late", goal: "weight", allergens: ["seafood"], desc: "양파와 양배추의 단맛이 연어의 기름진 풍미를 살림", texture: "진밥", ingredients: "생연어 20g, 양배추 15g, 양파 10g, 진밥 50g", recipe: ["1. 연어 찌기", "2. 양파/양배추 볶아 단맛 내고 밥과 끓이기"] },
    { id: "l59", name: "전복 감자 당근 진밥", age: "late", goal: "weight", allergens: ["seafood"], desc: "아기 원기 회복 1등 공신 전복을 푹 익혀 부드럽게", texture: "진밥", ingredients: "전복살 20g, 감자 15g, 당근 10g, 진밥 50g", recipe: ["1. 전복 내장 버리고 살만 쪄서 아주 잘게 얇게 다지기", "2. 야채/밥 끓이기"] },
    { id: "l60", name: "돼지고기 부추 양파 볶음밥", age: "late", goal: "weight", allergens: [], desc: "돼지고기와 최고의 궁합 부추! 향긋한 고기 볶음밥", texture: "무른 볶음밥", ingredients: "돼지안심 30g, 부추 10g, 양파 10g, 진밥 50g", recipe: ["1. 부추 아주 잘게 다지기", "2. 돼지고기/양파 바싹 볶다 부추/밥 섞기"] },
    { id: "l61", name: "게살 브로콜리 계란 진밥", age: "late", goal: "weight", allergens: ["shellfish", "egg"], desc: "게살수프 밥 버전! 목 넘김이 너무 부드러워 순삭", texture: "촉촉한 진밥", ingredients: "크래미 20g, 브로콜리 15g, 계란 1개, 진밥 50g", recipe: ["1. 브로콜리 다지기", "2. 육수 끓이다 밥/게살 넣고 마지막에 계란물 풀어 저어주기"] },
    { id: "l62", name: "노른자 토마토 두부 비빔밥", age: "late", goal: "iron", allergens: ["egg", "soy"], desc: "토마토달걀볶음(토달볶)에 두부를 넣어 영양 꽉 채운 비빔밥", texture: "비빔밥 스타일", ingredients: "계란 노른자 1개, 방울토마토 2개, 으깬 두부 20g, 진밥 50g", recipe: ["1. 토마토 껍질 까서 다지기", "2. 두부/토마토 볶다 노른자 으깨어 밥에 비비기"] },
    { id: "l63", name: "소고기 참깨 무 진밥", age: "late", goal: "poop", allergens: [], desc: "소고기 뭇국 베이스에 갈은 참깨를 넣어 고소함 폭발", texture: "국물 자박 진밥", ingredients: "소고기 30g, 무 15g, 참깨가루 1t, 진밥 50g", recipe: ["1. 고기/무 볶다 물 붓고 밥 졸이기", "2. 먹기 전 깨가루 솔솔"] },
    { id: "l64", name: "닭고기 렌틸콩 토마토 진밥", age: "late", goal: "iron", allergens: [], desc: "서양식 렌틸콩 스튜에 밥 말아먹는 느낌의 특식", texture: "진밥", ingredients: "닭안심 30g, 레드렌틸콩 10g, 방울토마토 2개, 진밥 50g", recipe: ["1. 렌틸콩 삶고 토마토 다지기", "2. 고기 볶다 재료 다 넣고 밥과 끓이기"] },
    { id: "l65", name: "소고기 배추 표고버섯 진밥", age: "late", goal: "iron", allergens: [], desc: "배추의 시원함과 표고의 감칠맛이 전골 느낌을 내는 밥", texture: "진밥", ingredients: "소고기 30g, 배추 15g, 표고버섯 10g, 진밥 50g", recipe: ["1. 배추잎/표고 다지기", "2. 고기와 육수에 볶다 밥 넣고 졸이기"] },

    // ---------------- [공장장 3차 추가분: 완료기 유아식 10종] ----------------
    { id: "d36", name: "소고기 야채 꼬마김밥", age: "done", goal: "iron", allergens: [], desc: "나들이 필수품! 무조미 김으로 돌돌 만 아기 김밥", texture: "핑거푸드 밥", ingredients: "다진 소고기 20g, 당근/단무지(물에씻어) 10g, 무조미김, 밥 70g", recipe: ["1. 소고기/당근 볶기", "2. 밥에 참기름 1방울 섞고 김을 4등분 하여 얇게 말기", "3. 한입 크기로 자르기"] },
    { id: "d37", name: "새우 브로콜리 크림 리조또", age: "done", goal: "weight", allergens: ["shellfish", "dairy", "flour"], desc: "생우유로 만든 꾸덕한 레스토랑 크림 리조또", texture: "꾸덕한 밥", ingredients: "새우살 30g, 브로콜리 20g, 우유 50ml, 아기치즈 1장, 밥", recipe: ["1. 새우/브로콜리 버터에 살짝 볶기", "2. 우유 부어 끓이다 밥/치즈 넣고 졸이기"] },
    { id: "d38", name: "대구살 감자 크로켓", age: "done", goal: "weight", allergens: ["seafood", "egg", "flour"], desc: "피시앤칩스 아기버전! 생선 안 먹는 아이들 대환장 파티", texture: "겉바속촉 튀김", ingredients: "대구살 30g, 감자 1개, 계란물, 빵가루", recipe: ["1. 감자 쪄서 으깨고 찐 대구살 섞기", "2. 동그랗게 빚어 계란/빵가루 묻혀 에프 10분"] },
    { id: "d39", name: "닭가슴살 콩나물 무침 (반찬)", age: "done", goal: "all", allergens: ["soy"], desc: "고기와 야채를 한 번에 먹이는 삼삼한 아기 반찬", texture: "아삭한 나물 반찬", ingredients: "닭가슴살 40g, 콩나물 30g, 아기간장 1t, 참기름/깨", recipe: ["1. 닭가슴살 푹 삶아 잘게 결대로 찢기", "2. 콩나물 데쳐 다지기", "3. 간장/참기름 조물조물"] },
    { id: "d40", name: "전복 야채 버터 볶음 (반찬)", age: "done", goal: "weight", allergens: ["seafood", "dairy"], desc: "돌아기 생일상 반찬 1티어. 버터향 가득 쫄깃 전복", texture: "버터 볶음", ingredients: "전복 1마리, 파프리카/양파 20g, 무염버터 1t", recipe: ["1. 전복 내장 빼고 얇게 칼집 내기", "2. 야채 다져 버터 두른 팬에 전복과 노릇하게 굽기"] },
    { id: "d41", name: "토마토 해산물 파스타", age: "done", goal: "iron", allergens: ["seafood", "flour"], desc: "생토마토로 소스를 낸 안전하고 맛있는 아기 해물 스파게티", texture: "면 요리", ingredients: "새우살/오징어 다진것 30g, 토마토 1개, 아기면 50g", recipe: ["1. 토마토 데쳐 껍질 까고 으깨기", "2. 해산물 볶다 토마토 넣어 끓이기", "3. 삶은 면 비비기"] },
    { id: "d42", name: "돼지고기 숙주 볶음우동", age: "done", goal: "weight", allergens: ["soy", "flour"], desc: "아삭한 숙주와 쫄깃한 면발! 밥 안 먹을 때 치트키", texture: "볶음 우동", ingredients: "돼지안심 30g, 숙주 20g, 아기우동면 50g, 아기간장 1t", recipe: ["1. 우동면 삶아 자르기", "2. 고기 볶다 숙주, 면, 간장 넣고 센불에 빠르게 볶기"] },
    { id: "d43", name: "치즈 단호박 머핀", age: "done", goal: "poop", allergens: ["dairy", "egg", "flour"], desc: "밀가루 대신 쌀가루로 구워낸 달콤 짭짤 치즈빵", texture: "촉촉한 머핀", ingredients: "찐 단호박 30g, 아기치즈 1장, 쌀가루(또는 밀가루) 30g, 계란 1개", recipe: ["1. 단호박 으깨 계란, 가루 섞기", "2. 치즈 찢어 넣고 오븐/에프 170도 15분 굽기"] },
    { id: "d44", name: "시금치 두부 무침 (반찬)", age: "done", goal: "iron", allergens: ["soy"], desc: "가장 기본이 되는 한식 아기 반찬. 부드러워 잘 먹음", texture: "촉촉한 나물", ingredients: "시금치 20g, 두부 30g, 참기름 1방울, 깨가루", recipe: ["1. 시금치 데쳐 물기 짜고 다지기", "2. 두부 끓는물에 데쳐 물기 짜고 으깨기", "3. 참기름 조물조물"] },
    { id: "d45", name: "밥새우 애호박 볶음 (반찬)", age: "done", goal: "all", allergens: ["shellfish"], desc: "건새우보다 작고 부드러운 밥새우를 활용한 감칠맛 폭발 반찬", texture: "볶음 반찬", ingredients: "밥새우(아주 작은 새우) 10g, 애호박 30g, 현미유 1t", recipe: ["1. 애호박 채 썰어 다지기", "2. 밥새우 마른 팬에 볶아 비린내 날리기", "3. 기름 두르고 애호박과 함께 볶기"] }, ];