// ==========================================
// 🗄️ 육아메이트 DB (데이터 전담 파일 V13.6 - 링크 철통 방어 패치)
// ==========================================

const carDB = {
    'ray': { name: '기아 레이', limitDepth: 35, limitHeight: 80, vol: 319 },
    'casper': { name: '캐스퍼/모닝', limitDepth: 45, limitHeight: 70, vol: 301 },
    'avante': { name: '아반떼(K3)', limitDepth: 100, limitHeight: 45, vol: 474 },
    'sonata': { name: '쏘나타(K5)', limitDepth: 105, limitHeight: 48, vol: 510 },
    'grandeur': { name: '그랜저/G80', limitDepth: 110, limitHeight: 50, vol: 480 },
    'seltos': { name: '셀토스/코나', limitDepth: 80, limitHeight: 70, vol: 498 },
    'qm6': { name: '르노 QM6', limitDepth: 95, limitHeight: 75, vol: 676 },
    'sorento': { name: '쏘렌토/싼타페', limitDepth: 105, limitHeight: 80, vol: 705 },
    'palisade': { name: '팰리세이드', limitDepth: 115, limitHeight: 85, vol: 1297 },
    'carnival': { name: '카니발(3열)', limitDepth: 30, limitHeight: 100, vol: 400 } // 3열 펴면 트렁크 극악임
};

const strollerData = [
    // --- [디럭스 12종] ---
    /* 1 */ { name: "스토케 익스플로리 X", type: "디럭스", price: 1850000, hiddenTax: { cost: 85000, items: "컵홀더(3.5만), 썬쉐이드(5만) 필수" }, asInfo: { status: "warn", text: "무상 3년 이후 부품 교체 수리비 다소 높음" }, specs: { weight: 13.4, folding: "시트 분리 필수 (일체형 폴딩 불가)", angle: "175도 조절", cabin: "기내 ❌" }, foldedDims: [56, 89, 45], expand: "불가 ❌", width: 56, foldedRef: "28인치 캐리어 1.5배", backrest: 54, adapter: { maxi: "전용 어댑터(7만) 필요", stokke: "직결 가능 ⭕" }, trunk: "SUV 전용", road: "턱 충격 완벽 흡수", wash: "구조 복잡", flight: "하이체어 완벽 대체 (식당 프리패스)", joint: "리프팅 유의 (아빠 전담)", flaw: "독보적 하이시트, 시트 빼서 접어야 하는 번거로움", tags: { env: 'apartment', car: 'suv', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'official', url: 'https://www.stokke.com/KOR/ko-kr/home', label: '스토케 한국 공식몰 혜택' } },
    /* 2 */ { name: "부가부 폭스 5", type: "디럭스", price: 2100000, hiddenTax: { cost: 230000, items: "컵홀더, 브리지 캐노피 등 별도" }, asInfo: { status: "good", text: "글로벌 4년 보증 우수. 해외 배송 대기 존재" }, specs: { weight: 10.4, folding: "원핸드 폴딩 (일체형 폴딩 가능)", angle: "175도 조절", cabin: "기내 ❌" }, foldedDims: [34, 60, 90], expand: "불가 ❌", width: 60, foldedRef: "28인치 캐리어 급", backrest: 59, adapter: { maxi: "전용 어댑터(7.5만) 필요", stokke: "호환 불가 ❌" }, trunk: "세단/SUV 적재 가능", road: "전륜 서스펜션 우수", wash: "탈부착 직관적", flight: "구형 개찰구 턱걸이", joint: "디럭스치고 가벼움", flaw: "핸들링 1티어, 악마 같은 악세사리 가격", tags: { env: 'apartment', car: 'suv', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'official', url: 'https://www.bugaboo.com/kr-ko', label: '부가부 코리아 공식몰' } },
    /* 3 */ { name: "싸이벡스 프리암", type: "디럭스", price: 2050000, hiddenTax: { cost: 35000, items: "컵홀더 별도" }, asInfo: { status: "warn", text: "정품 등록 시 원활. 직구품 수리 100% 불가" }, specs: { weight: 13.1, folding: "수동 폴딩", angle: "180도 조절", cabin: "기내 ❌" }, foldedDims: [31, 60, 85], expand: "불가 ❌", width: 60, foldedRef: "28인치 캐리어 급", backrest: 53, adapter: { maxi: "어댑터 기본 포함 ⭕", stokke: "호환 불가 ❌" }, trunk: "SUV 권장", road: "독립 서스펜션 최고", wash: "패브릭 분리 쉬움", flight: "테이블 호환 우수", joint: "손목 무리", flaw: "로즈골드 프레임의 미친 디자인, 진입장벽 높음", tags: { env: 'apartment', car: 'suv', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 검색 결과 확인' } },
    /* 4 */ { name: "어파베이비 비스타 V2", type: "디럭스", price: 1750000, hiddenTax: { cost: 0, items: "방풍커버 등 풀패키지 혜자" }, asInfo: { status: "good", text: "뼈대가 튼튼해 고장이 적고 A/S 응대 준수" }, specs: { weight: 12.4, folding: "수동 폴딩", angle: "175도 조절", cabin: "기내 ❌" }, foldedDims: [33, 65, 81], expand: "가능 ⭕ (럼블시트 장착 시 연년생/쌍둥이용 변신)", width: 65, foldedRef: "이민용 대형 캐리어 급", backrest: 53, adapter: { maxi: "비스타 전용 어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "SUV 전용", road: "묵직한 돌파력", wash: "뼈대 해체 힘듦", flight: "일반 개찰구 불가", joint: "리프팅 코어힘 요구", flaw: "초대형 장바구니, 세단 트렁크엔 적재 불가 수준", tags: { env: 'apartment', car: 'suv', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 실시간 최저가' } },
    /* 5 */ { name: "에그 3", type: "디럭스", price: 1950000, hiddenTax: { cost: 50000, items: "라이너 등 별도 구매" }, asInfo: { status: "warn", text: "곡선 프레임 긁힘 민감, 수리 대기 있음" }, specs: { weight: 12.5, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [32, 59, 71], expand: "가능 ⭕ (탠덤 어댑터로 연년생 탑승)", width: 59, foldedRef: "28인치 캐리어 급", backrest: 50, adapter: { maxi: "전용 어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "SUV 권장", road: "주행감 매우 우수", wash: "건조 느림", flight: "좁은 카페 불편", joint: "바닥 눕힘 폴딩", flaw: "계란형 디자인 원탑, 장바구니가 매우 좁음", tags: { env: 'apartment', car: 'suv', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'official', url: 'https://eggstroller.co.kr', label: '에그 코리아 공식몰' } },
    /* 6 */ { name: "오이스터 3", type: "디럭스", price: 1150000, hiddenTax: { cost: 0, items: "기본 구성품 넉넉함" }, asInfo: { status: "good", text: "국내 총판 엠베이비 수리망 원활" }, specs: { weight: 10.4, folding: "일체형 폴딩", angle: "170도", cabin: "기내 ❌" }, foldedDims: [37, 57, 71], expand: "불가 ❌", width: 57, foldedRef: "24인치 캐리어 급", backrest: 49, adapter: { maxi: "어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "세단 적재 가능", road: "서스펜션 양호", wash: "일반적", flight: "무난함", joint: "디럭스치고 접기 쉬움", flaw: "디럭스계의 가성비, 서스펜션은 하이엔드 대비 아쉬움", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑 결과 검색' } },
    /* 7 */ { name: "뉴나 데미 그로우", type: "디럭스", price: 1650000, hiddenTax: { cost: 0, items: "기본 구성 준수" }, asInfo: { status: "good", text: "본사 정책이 탄탄하여 피드백 좋음" }, specs: { weight: 13.8, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [38, 60, 89], expand: "가능 ⭕", width: 60, foldedRef: "대형 캐리어 급", backrest: 52, adapter: { maxi: "뉴나 기본 호환", stokke: "호환 불가 ❌" }, trunk: "SUV 전용", road: "탱크급 주행", wash: "세탁망 필수", flight: "크기 부담", joint: "압도적 무게", flaw: "대한민국 최고 체급 무게 (아빠 필수)", tags: { env: 'apartment', car: 'suv', baby: 'twins', parent: 'strong', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑 통합검색' } },
    /* 8 */ { name: "줄즈 지오 3", type: "디럭스", price: 1800000, hiddenTax: { cost: 60000, items: "전용 액세서리 별도" }, asInfo: { status: "good", text: "엔픽스 공식 보증, 사후 관리 철저" }, specs: { weight: 13.0, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [35, 60, 92], expand: "가능 ⭕ (위아래 듀오 셋업 특화)", width: 60, foldedRef: "대형 캐리어 급", backrest: 53, adapter: { maxi: "어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "SUV 전용", road: "대형 바퀴 돌파력", wash: "무난함", flight: "좁은 곳 불편", joint: "양손 폴딩", flaw: "확장성 우수, 모닝/레이 트렁크 절대 불가", tags: { env: 'apartment', car: 'suv', baby: 'twins', parent: 'strong', budget: 'premium' }, affiliate: { type: 'official', url: 'https://my-joolz.co.kr', label: '줄즈 코리아 공식몰' } },
    /* 9 */ { name: "잉글레시나 앱티카", type: "디럭스", price: 1450000, hiddenTax: { cost: 0, items: "한국형 풀패키지 증정" }, asInfo: { status: "good", text: "끄레델 A/S 훌륭, 부품비 저렴" }, specs: { weight: 11.8, folding: "원핸드 매직 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [42, 50, 90], expand: "불가 ❌", width: 50, foldedRef: "28인치 캐리어 급", backrest: 53, adapter: { maxi: "미지원 ❌", stokke: "호환 불가 ❌" }, trunk: "세단 가능", road: "유연한 주행", wash: "편리함", flight: "디럭스치고 슬림", joint: "원핸드 쾌적", flaw: "접고 펴기 예술, 시트 포지션이 다소 낮음", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCrzivnkL6', label: '🚀 쿠팡 로켓배송 최저가' } },
    /* 10 */{ name: "페도라 L4", type: "디럭스", price: 550000, hiddenTax: { cost: 0, items: "기본 패키지" }, asInfo: { status: "good", text: "국산 브랜드 A/S 준수" }, specs: { weight: 9.5, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [35, 60, 80], expand: "불가 ❌", width: 60, foldedRef: "28인치 캐리어 급", backrest: 51, adapter: { maxi: "호환 불가 ❌", stokke: "호환 불가 ❌" }, trunk: "세단 꽉참", road: "튼튼함", wash: "무난", flight: "크기 있음", joint: "폴딩 뻑뻑함", flaw: "가성비 우수, 폴딩 관절 뻑뻑함", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 통합 검색 이동' } },
    /* 11 */{ name: "리안 스핀 로얄", type: "디럭스", price: 650000, hiddenTax: { cost: 0, items: "요람 포함 세트" }, asInfo: { status: "good", text: "국산 에이원 택배 수리망 최고" }, specs: { weight: 11.2, folding: "수동 폴딩", angle: "180도", cabin: "기내 ❌" }, foldedDims: [40, 58, 85], expand: "불가 ❌", width: 58, foldedRef: "28인치 캐리어 1.5배", backrest: 48, adapter: { maxi: "호환 불가 ❌", stokke: "호환 불가 ❌" }, trunk: "SUV 전용", road: "무난함", wash: "요람 세척 까다로움", flight: "무거움", joint: "스핀 기능 특화", flaw: "시트 분리 없이 360도 회전, 부피가 매우 큼", tags: { env: 'apartment', car: 'suv', baby: 'newborn', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 최저가 가격비교' } },
    /* 12 */{ name: "하베 브미니", type: "디럭스", price: 1200000, hiddenTax: { cost: 0, items: "기본 구성품 우수" }, asInfo: { status: "warn", text: "인지도 낮아 사설 수리점 이용 제한" }, specs: { weight: 11.0, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [30, 59, 85], expand: "불가 ❌", width: 59, foldedRef: "28인치 캐리어 급", backrest: 50, adapter: { maxi: "어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "세단 가능", road: "디자인 특화", wash: "평범", flight: "무난함", joint: "디럭스 중 가벼움", flaw: "수려한 디자인, 인지도 부족", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 검색 결과 확인' } },

    // --- [절충형 12종] ---
    /* 13 */{ name: "싸이벡스 미오스", type: "절충형", price: 1350000, hiddenTax: { cost: 35000, items: "컵홀더 별도" }, asInfo: { status: "warn", text: "정품 등록 시 원활. 직구품 수리 불가" }, specs: { weight: 9.9, folding: "수동 폴딩", angle: "175도 조절", cabin: "기내 ❌" }, foldedDims: [33, 50, 75], expand: "불가 ❌", width: 50, foldedRef: "24인치 수하물 캐리어 급", backrest: 50, adapter: { maxi: "어댑터 박스 기본 포함 ⭕", stokke: "호환 불가 ❌" }, trunk: "세단 트렁크 유연 적재", road: "바퀴 작아 배수구 주의", wash: "메쉬라 건조 최강", flight: "좁은 핫플 프리패스", joint: "폴딩 손목 스냅 요구", flaw: "등받이 메쉬망으로 여름 아기 구세주, 서스펜션 아쉬움", tags: { env: 'mall', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 통합 검색' } },
    /* 14 */{ name: "잉글레시나 일렉타", type: "절충형", price: 1050000, hiddenTax: { cost: 0, items: "한국형 풀패키지 혜택" }, asInfo: { status: "good", text: "국내 총판 끄레델 A/S망 탄탄함" }, specs: { weight: 8.7, folding: "원액션 매직 폴딩", angle: "175도 조절", cabin: "기내 ❌" }, foldedDims: [30, 50, 73], expand: "불가 ❌", width: 50, foldedRef: "24인치 캐리어 급", backrest: 54, adapter: { maxi: "공식 미지원 ❌", stokke: "호환 불가 ❌" }, trunk: "국산 세단 쾌적 적재", road: "쇼핑몰/대리석 최적", wash: "버튼 시인성 우수", flight: "KTX 통로 돌파", joint: "8.7kg 경량 쾌적", flaw: "엄마 혼자 트렁크 싣기 가능! 디럭스 안정성엔 다소 부족", tags: { env: 'mall', car: 'sedan', baby: 'giant', parent: 'joint', budget: 'under100' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCrwMoyEeW', label: '🚀 쿠팡 로켓배송' } },
    /* 15 */{ name: "실버크로스 듄", type: "절충형", price: 1550000, hiddenTax: { cost: 0, items: "방풍커버 등 프로모션 잦음" }, asInfo: { status: "good", text: "국내 총판 친절도 최상" }, specs: { weight: 11.5, folding: "원핸드 폴딩", angle: "175도 조절", cabin: "기내 ❌" }, foldedDims: [35, 58, 68], expand: "불가 ❌", width: 58, foldedRef: "24인치 캐리어 급", backrest: 54, adapter: { maxi: "전용 어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "세단 여유 적재", road: "밀착 주행 우수", wash: "세탁망 필수", flight: "개찰구 간당간당", joint: "11.5kg 관절 부담", flaw: "디자인 원탑, 절충형 치고 무게가 디럭스 급", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 검색 결과' } },
    /* 16 */{ name: "부가부 드래곤플라이", type: "절충형", price: 1450000, hiddenTax: { cost: 100000, items: "컵홀더, 범퍼바 별도" }, asInfo: { status: "good", text: "글로벌 보증 확실" }, specs: { weight: 7.9, folding: "원핸드 스탠드업", angle: "175도", cabin: "기내 ❌" }, foldedDims: [36, 52, 90], expand: "불가 ❌", width: 52, foldedRef: "24인치 캐리어 급", backrest: 58, adapter: { maxi: "어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "세단 용이", road: "최상 핸들링", wash: "탈착 편함", flight: "일반 마트 무난", joint: "허리 안굽히는 폴딩 원탑", flaw: "배시넷 단 채로 한손 접기 가능! (예술적 폴딩), 가격 사악함", tags: { env: 'mall', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'premium' }, affiliate: { type: 'official', url: 'https://www.bugaboo.com/kr-ko', label: '부가부 코리아 공식몰' } },
    /* 17 */{ name: "어파베이비 크루즈 V2", type: "절충형", price: 1250000, hiddenTax: { cost: 0, items: "풀패키지 증정" }, asInfo: { status: "good", text: "프레임 내구성 최고 수준" }, specs: { weight: 11.6, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [42, 58, 84], expand: "가능 ⭕ (피기백 보드 장착)", width: 58, foldedRef: "28인치 캐리어 급", backrest: 53, adapter: { maxi: "어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "세단 꽉 참", road: "안정감 우수", wash: "일반적", flight: "장바구니 깡패", joint: "무거운 편", flaw: "마트 장보기 최강의 수납력, 절충형치고 부피 큼", tags: { env: 'apartment', car: 'suv', baby: 'giant', parent: 'strong', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑 검색' } },
    /* 18 */{ name: "뉴나 트리브 넥스트", type: "절충형", price: 1150000, hiddenTax: { cost: 0, items: "풀패키지 증정" }, asInfo: { status: "good", text: "잔고장 덜하고 A/S 무난" }, specs: { weight: 8.7, folding: "원핸드 폴딩", angle: "170도", cabin: "기내 ❌" }, foldedDims: [32, 52, 64], expand: "불가 ❌", width: 52, foldedRef: "24인치 캐리어 급", backrest: 51, adapter: { maxi: "뉴나 바구니 호환", stokke: "호환 불가 ❌" }, trunk: "세단 쏙 들어감", road: "서스펜션 준수", wash: "일반적", flight: "무난함", joint: "부드러운 폴딩", flaw: "폴딩/언폴딩 매우 쾌적, 디자인 호불호 다소 있음", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑' } },
    /* 19 */{ name: "줄즈 허브 플러스", type: "절충형", price: 1100000, hiddenTax: { cost: 40000, items: "컵홀더 별도" }, asInfo: { status: "good", text: "엔픽스 사후관리 철저" }, specs: { weight: 10.9, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [31, 53, 63], expand: "불가 ❌", width: 53, foldedRef: "24인치 캐리어 급", backrest: 52, adapter: { maxi: "어댑터 필요", stokke: "호환 불가 ❌" }, trunk: "세단 무난", road: "LED 감성 주행", wash: "무난", flight: "스탠딩 불안", joint: "폴딩 무거움", flaw: "야간 주행 LED 불빛 이쁨, 접고 나서 셀프스탠딩 안됨", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'strong', budget: 'under100' }, affiliate: { type: 'official', url: 'https://my-joolz.co.kr', label: '줄즈 코리아몰' } },
    /* 20 */{ name: "리안 솔로", type: "절충형", price: 350000, hiddenTax: { cost: 0, items: "에이원 공식몰 풀패키지" }, asInfo: { status: "good", text: "부품 싸고 전국 수리망 빠름" }, specs: { weight: 8.9, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [30, 50, 60], expand: "불가 ❌", width: 50, foldedRef: "24인치 캐리어 급", backrest: 48, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "모든 차종 슬림 적재", road: "핸들링 다소 묵직", wash: "직관적", flight: "아파트 엘베 최적", joint: "관절부 뻑뻑", flaw: "국민 가성비 절충형, 트래블 시스템 호환 불가", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under40' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCrlC4MXe0', label: '🚀 쿠팡 로켓배송 최저가' } },
    /* 21 */{ name: "페도라 S9", type: "절충형", price: 450000, hiddenTax: { cost: 0, items: "기본 구성" }, asInfo: { status: "good", text: "국산 브랜드 무난한 A/S" }, specs: { weight: 9.5, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [38, 58, 78], expand: "불가 ❌", width: 58, foldedRef: "28인치 캐리어 급", backrest: 49, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "SUV 권장", road: "무난", wash: "무난", flight: "부피 큼", joint: "다소 무거움", flaw: "가성비 모델", tags: { env: 'apartment', car: 'suv', baby: 'newborn', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑 최저가' } },
    /* 22 */{ name: "도노도노 블랑", type: "절충형", price: 450000, hiddenTax: { cost: 0, items: "풀세트" }, asInfo: { status: "good", text: "국산 브랜드 A/S 원활" }, specs: { weight: 8.5, folding: "원터치 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [30, 50, 60], expand: "불가 ❌", width: 50, foldedRef: "24인치 캐리어 급", backrest: 48, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "세단 무난", road: "가벼운 주행", wash: "쉬움", flight: "마트용 최적", joint: "가벼움", flaw: "무난한 가성비, 약간의 흔들림 있음", tags: { env: 'mall', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑' } },
    /* 23 */{ name: "다이치 앨리", type: "절충형", price: 550000, hiddenTax: { cost: 0, items: "카시트 세트 프로모션" }, asInfo: { status: "good", text: "카시트 1등 기업의 든든한 A/S" }, specs: { weight: 9.5, folding: "수동 폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [30, 55, 65], expand: "불가 ❌", width: 55, foldedRef: "24인치 캐리어 급", backrest: 50, adapter: { maxi: "다이치 전용 어댑터", stokke: "호환 ❌" }, trunk: "세단 무난", road: "안정감 우수", wash: "무난", flight: "일반문 패스", joint: "평범", flaw: "카시트 호환 특화 모델", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 통합 검색 연결' } },
    /* 24 */{ name: "하베스 절충형", type: "절충형", price: 600000, hiddenTax: { cost: 0, items: "기본 구성" }, asInfo: { status: "warn", text: "부품 수급 간헐적 지연" }, specs: { weight: 9.0, folding: "수동 폴딩", angle: "170도", cabin: "기내 ❌" }, foldedDims: [30, 50, 65], expand: "불가 ❌", width: 50, foldedRef: "24인치 캐리어 급", backrest: 50, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "세단 무난", road: "평범", wash: "평범", flight: "평범", joint: "평범", flaw: "중고가 당근마켓 방어율 약함", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑' } },

    // --- [휴대용 15종] ---
    /* 25 */{ name: "리안 그램플러스", type: "휴대용", price: 298000, hiddenTax: { cost: 0, items: "식판, 가방 등 풀패키지" }, asInfo: { status: "good", text: "국내 브랜드의 압도적 A/S 편의성" }, specs: { weight: 5.2, folding: "중력 오토폴딩", angle: "175도", cabin: "기내 ⚠️" }, foldedDims: [24, 43, 54], expand: "불가 ❌", width: 43, foldedRef: "20인치 기내용 쏙", backrest: 45, adapter: { maxi: "오토폴딩 구조상 불가", stokke: "불가 ❌" }, trunk: "틈새 적재 완벽", road: "실내 추천", wash: "세탁기 용이", flight: "LCC(저가항공) 게이트컷 간혹 발생", joint: "원터치 오토폴딩 관절 보호 완벽", flaw: "국민 가성비 오토폴딩, 서스펜션(흔들림) 약함", tags: { env: 'mall', car: 'compact', baby: 'newborn', parent: 'joint', budget: 'under40' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCrdWFUeUm', label: '🚀 쿠팡 로켓배송 최저가' } },
    /* 26 */{ name: "잉글레시나 퀴드3", type: "휴대용", price: 490000, hiddenTax: { cost: 0, items: "풀패키지 (최신버전)" }, asInfo: { status: "good", text: "끄레델 수리 원활" }, specs: { weight: 5.9, folding: "수동 폴딩", angle: "175도", cabin: "기내 ⭕" }, foldedDims: [17, 46, 58], expand: "불가 ❌", width: 46, foldedRef: "17cm 극강 슬림", backrest: 42, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "트렁크 틈새 쏙", road: "충격 전달 주의", wash: "쉬움", flight: "슬림해서 얇음", joint: "바닥 눕혀서 폴딩", flaw: "접었을 때 두께 극강 슬림, 등받이가 좀 짧음", tags: { env: 'mall', car: 'flight', baby: 'newborn', parent: 'joint', budget: 'under100' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCrtSAwS4q', label: '🚀 쿠팡 로켓배송 (퀴드3)' } },
    /* 27 */{ name: "줄즈 에어 플러스", type: "휴대용", price: 780000, hiddenTax: { cost: 110000, items: "안전바, 레그레스트 별도 필수" }, asInfo: { status: "warn", text: "사용 중 폴딩 관절 뻑뻑함 이슈 존재" }, specs: { weight: 6.0, folding: "원액션 폴딩", angle: "170도", cabin: "기내 ⚠️" }, foldedDims: [21, 45, 53], expand: "불가 ❌", width: 45, foldedRef: "20인치 기내용 쏙", backrest: 55, adapter: { maxi: "전용 어댑터(🚨분리 필수)", stokke: "호환 ❌" }, trunk: "경차 바닥 적재", road: "특허 서스펜션 최고", wash: "얇아 건조 빠름", flight: "LCC 수하물 게이트컷 확률 존재 (요요보다 살짝 김)", joint: "접을 땐 양손 필수", flaw: "휴대용 핸들링 원탑 및 긴 등받이, 액세서리 가격 창렬", tags: { env: 'mall', car: 'compact', baby: 'giant', parent: 'joint', budget: 'under100' }, affiliate: { type: 'official', url: 'https://my-joolz.co.kr', label: '줄즈 코리아 공식몰' } },
    /* 28 */{ name: "베이비젠 요요2", type: "휴대용", price: 790000, hiddenTax: { cost: 100000, items: "레그레스트 별도, 안전바 사제 필수" }, asInfo: { status: "bad", text: "병행/직구 프레임 부러지면 사설행 강제" }, specs: { weight: 6.2, folding: "수동 2스텝", angle: "145도", cabin: "기내 ⭕" }, foldedDims: [18, 44, 52], expand: "가능 ⭕ (요요 커넥트 장착)", width: 44, foldedRef: "20인치 기내용 널널", backrest: 43, adapter: { maxi: "전용 어댑터(🚨분리 필수)", stokke: "호환 ❌" }, trunk: "경차 프리패스", road: "큰 턱 걸림 주의", wash: "컬러팩 세탁 쉬움", flight: "전 세계 LCC 기내 반입 보장 1티어", joint: "접을 때 허리 깊숙이 숙여야 함", flaw: "기내 반입의 교과서, 등받이가 짧아 애가 크면 머리가 나옴", tags: { env: 'mall', car: 'flight', baby: 'newborn', parent: 'joint', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 통합 검색 우회' } },
    /* 31 */{ name: "해밀턴 X1 플러스", type: "휴대용", price: 890000, hiddenTax: { cost: 0, items: "풀패키지" }, asInfo: { status: "good", text: "자석버클 등 고장 적음" }, specs: { weight: 7.3, folding: "오토폴딩", angle: "170도", cabin: "기내 ❌" }, foldedDims: [27, 45, 57], expand: "불가 ❌", width: 45, foldedRef: "기내 선반 초과", backrest: 52, adapter: { maxi: "어댑터 필요", stokke: "호환 ❌" }, trunk: "세단 무난", road: "대리석 최적", wash: "무난", flight: "수하물 위탁 필수 (기내반입 거의 불가)", joint: "중력 폴딩 손목 보호", flaw: "마술같은 오토폴딩 최고, 7.3kg라 기내 반입 힘듦", tags: { env: 'mall', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 검색' } },
    /* 32 */{ name: "타보 플렉스 탭3", type: "휴대용", price: 320000, hiddenTax: { cost: 0, items: "풀패키지" }, asInfo: { status: "good", text: "국내 A/S 원활" }, specs: { weight: 6.8, folding: "오토폴딩", angle: "175도", cabin: "기내 ❌" }, foldedDims: [28, 46, 54], expand: "불가 ❌", width: 46, foldedRef: "기내 간당간당", backrest: 48, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "세단 무난", road: "주행력 좋음", wash: "무난", flight: "위탁 권장", joint: "무게감 있음", flaw: "가성비 우수, 오토폴딩치고 약간 무거움", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under40' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCrLPOrO9c', label: '🚀 쿠팡 로켓배송 최저가' } },
    /* 33 */{ name: "와이업 지니제로3", type: "휴대용", price: 280000, hiddenTax: { cost: 0, items: "식판 트레이 필수 포함" }, asInfo: { status: "good", text: "국산 가성비 수리망" }, specs: { weight: 6.5, folding: "오토폴딩", angle: "175도", cabin: "기내 ⚠️" }, foldedDims: [26, 45, 56], expand: "불가 ❌", width: 45, foldedRef: "기내 간당간당", backrest: 46, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "세단 무난", road: "핸들링 준수", wash: "식판 분리 편함", flight: "LCC 게이트컷 주의", joint: "오토폴딩 편함", flaw: "국민 식판 유모차 대명사, 프레임 잔고장 다소 있음", tags: { env: 'mall', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under40' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑 통합검색' } },
    /* 34 */{ name: "어파베이비 미누 V2", type: "휴대용", price: 650000, hiddenTax: { cost: 0, items: "기본 구성" }, asInfo: { status: "good", text: "프레임 튼튼함" }, specs: { weight: 7.6, folding: "원핸드", angle: "170도", cabin: "기내 ❌" }, foldedDims: [29, 52, 58], expand: "불가 ❌", width: 52, foldedRef: "부피 큰 편", backrest: 50, adapter: { maxi: "전용 어댑터", stokke: "호환 ❌" }, trunk: "세단 무난", road: "안정감 우수", wash: "무난", flight: "위탁 필수", joint: "휴대용 치고 무거움", flaw: "휴대용계의 장바구니 깡패, 무거워서 기내 반입 ❌", tags: { env: 'mall', car: 'sedan', baby: 'giant', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 통합 검색' } },
    /* 35 */{ name: "마이크라라이트 프로폴드", type: "휴대용", price: 500000, hiddenTax: { cost: 0, items: "무난" }, asInfo: { status: "warn", text: "부품 조달 지연 간혹" }, specs: { weight: 7.0, folding: "수동", angle: "170도", cabin: "기내 ⚠️" }, foldedDims: [25, 45, 55], expand: "불가 ❌", width: 45, foldedRef: "무난", backrest: 48, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "경차 무난", road: "특이한 해먹 시트", wash: "무난", flight: "게이트컷 주의", joint: "무난", flaw: "독특한 해먹 디자인 호불호 갈림", tags: { env: 'mall', car: 'compact', baby: 'newborn', parent: 'joint', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 검색 결과' } },
    /* 36 */{ name: "엘레니어 레니", type: "휴대용", price: 250000, hiddenTax: { cost: 0, items: "가성비" }, asInfo: { status: "good", text: "국산 A/S" }, specs: { weight: 5.8, folding: "수동", angle: "170도", cabin: "기내 ⭕" }, foldedDims: [22, 45, 55], expand: "불가 ❌", width: 45, foldedRef: "슬림", backrest: 45, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "모두 무난", road: "통통 튐", wash: "쉬움", flight: "무사통과", joint: "가벼움", flaw: "초가성비이나 흔들림이 다소 심함", tags: { env: 'mall', car: 'flight', baby: 'newborn', parent: 'joint', budget: 'under40' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑' } },
    /* 37 */{ name: "베이비조거 시티투어2", type: "휴대용", price: 450000, hiddenTax: { cost: 0, items: "-" }, asInfo: { status: "good", text: "무난" }, specs: { weight: 6.5, folding: "폴딩", angle: "170도", cabin: "기내 ⚠️" }, foldedDims: [20, 45, 55], expand: "불가 ❌", width: 45, foldedRef: "-", backrest: 45, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "경차", road: "무난", wash: "무난", flight: "주의", joint: "무난", flaw: "전체적으로 무난함", tags: { env: 'mall', car: 'compact', baby: 'newborn', parent: 'joint', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑' } },
    /* 38 */{ name: "마더케어 나노", type: "휴대용", price: 200000, hiddenTax: { cost: 0, items: "-" }, asInfo: { status: "warn", text: "-" }, specs: { weight: 5.5, folding: "수동", angle: "150도", cabin: "기내 ⭕" }, foldedDims: [25, 45, 54], expand: "불가 ❌", width: 45, foldedRef: "-", backrest: 42, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "경차", road: "통통튐", wash: "쉬움", flight: "패스", joint: "가벼움", flaw: "초저가형 서브용", tags: { env: 'mall', car: 'flight', baby: 'newborn', parent: 'joint', budget: 'under40' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑' } },
    /* 39 */{ name: "퀴니 젯", type: "휴대용", price: 350000, hiddenTax: { cost: 0, items: "-" }, asInfo: { status: "good", text: "-" }, specs: { weight: 6.0, folding: "오토", angle: "170도", cabin: "기내 ⚠️" }, foldedDims: [28, 44, 55], expand: "불가 ❌", width: 44, foldedRef: "-", backrest: 45, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "경차", road: "무난", wash: "무난", flight: "위탁", joint: "무난", flaw: "무난", tags: { env: 'mall', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under40' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑' } },

    // --- [쌍둥이/웨건/트라이크 변종 11종] ---
    /* 40 */{ name: "부가부 동키 5", type: "쌍둥이", price: 2800000, hiddenTax: { cost: 300000, items: "확장셋, 컵홀더 별도" }, asInfo: { status: "good", text: "글로벌 보증" }, specs: { weight: 15.0, folding: "시트 분리", angle: "175도", cabin: "기내 ❌" }, foldedDims: [35, 60, 90], expand: "가능 ⭕ (모노->듀오->트윈 자유자재)", width: 74, foldedRef: "매우 거대함", backrest: 54, adapter: { maxi: "트윈 어댑터 필요", stokke: "호환 ❌" }, trunk: "대형 SUV 전용", road: "탱크급 주행", wash: "해체 힘듦", flight: "휠체어 게이트 필수", joint: "허리 박살 주의", flaw: "쌍둥이/연년생의 종착역. 단, 문 통과 시 폭 74cm 압박", tags: { env: 'apartment', car: 'suv', baby: 'twins', parent: 'strong', budget: 'premium' }, affiliate: { type: 'official', url: 'https://www.bugaboo.com/kr-ko', label: '부가부 한국 공홈 쌍둥이팩' } },
    /* 41 */{ name: "베이비조거 시티투어2 더블", type: "쌍둥이", price: 800000, hiddenTax: { cost: 50000, items: "안전바 별도" }, asInfo: { status: "warn", text: "수리망 다소 아쉬움" }, specs: { weight: 10.3, folding: "원핸드", angle: "170도", cabin: "기내 ❌" }, foldedDims: [25, 66, 60], expand: "불가 ❌ (이미 2인용)", width: 66, foldedRef: "쌍둥이치고 슬림", backrest: 45, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "세단 가능", road: "가벼운 쌍둥이용", wash: "무난", flight: "일반문 간당간당", joint: "가벼운 쌍둥이", flaw: "가성비 쌍둥이 유모차, 차양막이 조금 짧음", tags: { env: 'mall', car: 'sedan', baby: 'twins', parent: 'joint', budget: 'under100' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCr1YWMU9Y', label: '🚀 쿠팡 로켓배송 최저가' } },
    /* 42 */{ name: "잉글레시나 트윈 스케치", type: "쌍둥이", price: 550000, hiddenTax: { cost: 0, items: "기본" }, asInfo: { status: "good", text: "끄레델 A/S 굳" }, specs: { weight: 12.5, folding: "원액션", angle: "170도", cabin: "기내 ❌" }, foldedDims: [30, 77, 60], expand: "불가 ❌ (이미 2인용)", width: 77, foldedRef: "거대함", backrest: 46, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "SUV", road: "무난", wash: "무난", flight: "휠체어 게이트 필수", joint: "무거움", flaw: "가성비 갑이나, 폭 77cm라 옛날 아파트 엘베 통과 빡셈", tags: { env: 'apartment', car: 'suv', baby: 'twins', parent: 'strong', budget: 'under100' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCrHbP7DUq', label: '🚀 쿠팡 로켓배송 최저가' } },
    /* 43 */{ name: "폼포라 N 웨건", type: "웨건", price: 850000, hiddenTax: { cost: 100000, items: "트레이, 모기장 별도" }, asInfo: { status: "good", text: "국내 제이엠아이엔티 수리 좋음" }, specs: { weight: 15.0, folding: "수동", angle: "등받이 고정", cabin: "기내 ❌" }, foldedDims: [40, 65, 95], expand: "가능 ⭕ (다인승 구조)", width: 65, foldedRef: "캠핑용 급 부피", backrest: 40, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "카니발 전용", road: "공원 최적화", wash: "청소기 흡입", flight: "게이트 제약 큼", joint: "끌고 다니기 무거움", flaw: "두 돌 이후 에버랜드 필수템. 세단 트렁크엔 절대 안 들어감", tags: { env: 'apartment', car: 'carnival', baby: 'twins', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑 통합 검색' } },
    /* 44 */{ name: "킨즈 엑스 웨건", type: "웨건", price: 650000, hiddenTax: { cost: 0, items: "기본" }, asInfo: { status: "good", text: "무난함" }, specs: { weight: 14.5, folding: "수동", angle: "고정", cabin: "기내 ❌" }, foldedDims: [35, 60, 90], expand: "가능 ⭕", width: 60, foldedRef: "웨건 중 슬림", backrest: 40, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "SUV", road: "아웃도어용", wash: "평범", flight: "게이트 제약", joint: "무거움", flaw: "가성비 웨건", tags: { env: 'apartment', car: 'suv', baby: 'twins', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 검색 이동' } },
    /* 46 */{ name: "타보 미니스트라이크", type: "트라이크", price: 170000, hiddenTax: { cost: 0, items: "기본" }, asInfo: { status: "good", text: "A/S 양호" }, specs: { weight: 4.8, folding: "폴딩", angle: "살짝 눕힘", cabin: "기내 ⭕" }, foldedDims: [18, 35, 65], expand: "불가 ❌", width: 35, foldedRef: "슬림", backrest: 38, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "모두 널널", road: "실내용", wash: "쉬움", flight: "기내 패스", joint: "가벼움", flaw: "어린이집 등하원 원탑! 단, 잠들면 목 꺾임", tags: { env: 'apartment', car: 'compact', baby: 'giant', parent: 'joint', budget: 'under40' }, affiliate: { type: 'coupang', url: 'https://link.coupang.com/a/eCrUx0fCMK', label: '🚀 쿠팡 로켓배송 최저가' } },
    /* 45 */{ name: "에이블 유모카", type: "트라이크", price: 150000, hiddenTax: { cost: 0, items: "기본" }, asInfo: { status: "warn", text: "바퀴 마모 잦음" }, specs: { weight: 4.5, folding: "우산 접기", angle: "고정", cabin: "기내 ⭕" }, foldedDims: [15, 30, 60], expand: "불가 ❌", width: 30, foldedRef: "극강 슬림", backrest: 35, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "모든 차 남음", road: "방지턱 매우 위험", wash: "프레임 닦음", flight: "기내 프리패스", joint: "깃털", flaw: "동네 마실용 최고봉, 과속방지턱 조심", tags: { env: 'mall', car: 'compact', baby: 'giant', parent: 'joint', budget: 'under40' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑 검색' } },
    /* 47 */{ name: "뷔르트 웨건", type: "웨건", price: 950000, hiddenTax: { cost: 0, items: "모기장 별도" }, asInfo: { status: "good", text: "튼튼함" }, specs: { weight: 16.0, folding: "수동", angle: "고정", cabin: "기내 ❌" }, foldedDims: [45, 65, 100], expand: "가능 ⭕", width: 65, foldedRef: "캠핑용", backrest: 40, adapter: { maxi: "호환 ❌", stokke: "호환 ❌" }, trunk: "카니발", road: "부드러움", wash: "어려움", flight: "불가", joint: "무거움", flaw: "프리미엄 웨건", tags: { env: 'apartment', car: 'carnival', baby: 'twins', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 통합 검색' } },
    /* 48 */{ name: "킨즈 무브2", type: "웨건", price: 450000, hiddenTax: { cost: 0, items: "-" }, asInfo: { status: "good", text: "국산" }, specs: { weight: 13.0, folding: "수동", angle: "고정", cabin: "기내 ❌" }, foldedDims: [35, 60, 90], expand: "가능 ⭕", width: 60, foldedRef: "웨건치고 슬림", backrest: 40, adapter: { maxi: "❌", stokke: "❌" }, trunk: "SUV", road: "무난", wash: "무난", flight: "불가", joint: "무난", flaw: "입문용 웨건", tags: { env: 'apartment', car: 'suv', baby: 'twins', parent: 'strong', budget: 'under100' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑' } },
    /* 49 */{ name: "에그 2 탠덤", type: "쌍둥이", price: 2100000, hiddenTax: { cost: 100000, items: "어댑터 별도" }, asInfo: { status: "warn", text: "스크래치 주의" }, specs: { weight: 14.5, folding: "수동", angle: "175도", cabin: "기내 ❌" }, foldedDims: [35, 59, 80], expand: "가능 ⭕", width: 59, foldedRef: "대형", backrest: 50, adapter: { maxi: "전용 필요", stokke: "❌" }, trunk: "SUV", road: "안정감 최고", wash: "느림", flight: "무거움", joint: "주의", flaw: "럭셔리 쌍둥이 유모차. 너무 무거움", tags: { env: 'apartment', car: 'suv', baby: 'twins', parent: 'strong', budget: 'premium' }, affiliate: { type: 'official', url: 'https://eggstroller.co.kr', label: '에그 한국 정식 수입몰' } },
    /* 50 */{ name: "마이크라라이트 투폴드", type: "쌍둥이", price: 1200000, hiddenTax: { cost: 0, items: "-" }, asInfo: { status: "warn", text: "부품 조달 간혹 지연" }, specs: { weight: 10.5, folding: "폴딩", angle: "170도", cabin: "기내 ❌" }, foldedDims: [30, 45, 105], expand: "가능 ⭕", width: 45, foldedRef: "골프백 형태", backrest: 48, adapter: { maxi: "❌", stokke: "❌" }, trunk: "세단", road: "공기타이어", wash: "무난", flight: "길어서 불편", joint: "무난", flaw: "연년생용 뒤에 서서 타는 보드 내장 특화. 접으면 골프백처럼 김", tags: { env: 'apartment', car: 'sedan', baby: 'twins', parent: 'strong', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 쇼핑 통합검색' } },
    
    /* 더미/단종 처리 우회 */
    { name: "스토케 크루시 (단종)", type: "디럭스", price: 1500000, hiddenTax: { cost: 0, items: "중고 전용" }, asInfo: { status: "bad", text: "단종으로 순정 부품 구하기 헬" }, specs: { weight: 14.0, folding: "시트 분리", angle: "175", cabin: "기내 ❌" }, foldedDims: [55, 90, 45], expand: "불가", width: 55, foldedRef: "크다", backrest: 54, adapter: { maxi: "❌", stokke: "❌" }, trunk: "SUV", road: "좋음", wash: "힘듦", flight: "불가", joint: "무거움", flaw: "단종됨", tags: { env: 'apartment', car: 'suv', baby: 'newborn', parent: 'strong', budget: 'premium' }, affiliate: { type: 'naver', url: '', label: '네이버 통합 검색' } },
    { name: "페도라 L3", type: "절충형", price: 300000, hiddenTax: { cost: 0, items: "-" }, asInfo: { status: "good", text: "-" }, specs: { weight: 8.0, folding: "수동", angle: "175", cabin: "기내 ❌" }, foldedDims: [30, 50, 60], expand: "불가", width: 50, foldedRef: "-", backrest: 48, adapter: { maxi: "❌", stokke: "❌" }, trunk: "세단", road: "무난", wash: "무난", flight: "무난", joint: "가벼움", flaw: "단종수순", tags: { env: 'apartment', car: 'sedan', baby: 'newborn', parent: 'joint', budget: 'under40' }, affiliate: { type: 'naver', url: '', label: '네이버 검색 결과' } }
];